import * as THREE from 'three';
import {CHUNK,EYE_H,LOAD_RADIUS,WALK_SPEED,RUN_SPEED,chunkKey,clamp,generateChunkData,canStand} from './world-v4.js';
import {buildChunk,disposeChunkGroup} from './renderer-v4.js';

const game=document.getElementById('game'),startScreen=document.getElementById('startScreen'),startBtn=document.getElementById('startBtn'),bootStatus=document.getElementById('bootStatus'),hud=document.getElementById('hud'),zoneName=document.getElementById('zoneName'),coordsEl=document.getElementById('coords'),joystick=document.getElementById('joystick'),stick=document.getElementById('stick'),lookHint=document.getElementById('lookHint');
let renderer,scene,camera,yawRig,pitchRig,localLight,yaw=0,pitch=0,started=false,lastTime=performance.now(),lastChunkKey='',joyPointer=null,lookPointer=null,lookX=0,lookY=0,baseLightIntensity=115;
const renderChunks=new Map(),keys=new Set(),motion={x:0,y:0};

function updateStreaming(force=false){const cx=Math.floor(yawRig.position.x/CHUNK),cz=Math.floor(yawRig.position.z/CHUNK),here=chunkKey(cx,cz);if(!force&&here===lastChunkKey)return;lastChunkKey=here;const wanted=new Set();for(let dz=-LOAD_RADIUS;dz<=LOAD_RADIUS;dz++)for(let dx=-LOAD_RADIUS;dx<=LOAD_RADIUS;dx++){const k=chunkKey(cx+dx,cz+dz);wanted.add(k);if(!renderChunks.has(k))renderChunks.set(k,buildChunk(scene,generateChunkData(cx+dx,cz+dz)));}for(const[k,g]of renderChunks)if(!wanted.has(k)){scene.remove(g);disposeChunkGroup(g);renderChunks.delete(k);}const current=generateChunkData(cx,cz).theme;zoneName.textContent=current.name;scene.fog.color.set(current.fog);scene.fog.density=current.id==='gallery'?.012:current.id==='service'?.021:current.id==='pool'?.015:.018;const clear=new THREE.Color(current.fog).multiplyScalar(.46);renderer.setClearColor(clear,1);localLight.color.set(current.light);baseLightIntensity=current.id==='service'?82:current.id==='gallery'?100:118;}
function initRenderer(){renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.55));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=false;game.appendChild(renderer.domElement);scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x77735b,.018);camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.05,150);yawRig=new THREE.Group();pitchRig=new THREE.Group();pitchRig.position.y=EYE_H;pitchRig.add(camera);yawRig.add(pitchRig);scene.add(yawRig);yawRig.position.set(CHUNK/2,0,CHUNK/2);scene.add(new THREE.HemisphereLight(0xfff5cf,0x38382f,.72));scene.add(new THREE.AmbientLight(0xffffff,.16));const sun=new THREE.DirectionalLight(0xfff2c8,.24);sun.position.set(-3,8,4);scene.add(sun);localLight=new THREE.PointLight(0xffefb2,baseLightIntensity,14,2);localLight.position.set(0,2.15,0);yawRig.add(localLight);updateStreaming(true);}
function setJoystickFromPointer(e){const r=joystick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.34;let dx=e.clientX-cx,dy=e.clientY-cy;const len=Math.hypot(dx,dy)||1;if(len>max){dx=dx/len*max;dy=dy/len*max;}motion.x=clamp(dx/max,-1,1);motion.y=clamp(dy/max,-1,1);stick.style.transform=`translate(${dx}px,${dy}px)`;}
function resetJoystick(){motion.x=motion.y=0;stick.style.transform='translate(0px,0px)';joyPointer=null;}
function installControls(){joystick.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();if(joyPointer!==null)return;joyPointer=e.pointerId;joystick.setPointerCapture?.(e.pointerId);setJoystickFromPointer(e);});joystick.addEventListener('pointermove',e=>{if(e.pointerId!==joyPointer)return;e.preventDefault();e.stopPropagation();setJoystickFromPointer(e);});const joyEnd=e=>{if(e.pointerId!==joyPointer)return;e.preventDefault();e.stopPropagation();resetJoystick();};joystick.addEventListener('pointerup',joyEnd);joystick.addEventListener('pointercancel',joyEnd);joystick.addEventListener('lostpointercapture',()=>{if(joyPointer!==null)resetJoystick();});renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'){renderer.domElement.requestPointerLock?.();return;}if(e.clientX<innerWidth*.38||lookPointer!==null)return;lookPointer=e.pointerId;lookX=e.clientX;lookY=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId);lookHint.style.opacity='0';});renderer.domElement.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||e.pointerId!==lookPointer)return;e.preventDefault();const dx=e.clientX-lookX,dy=e.clientY-lookY;lookX=e.clientX;lookY=e.clientY;applyLook(dx,dy,.0042);},{passive:false});const lookEnd=e=>{if(e.pointerId===lookPointer)lookPointer=null;};renderer.domElement.addEventListener('pointerup',lookEnd);renderer.domElement.addEventListener('pointercancel',lookEnd);document.addEventListener('mousemove',e=>{if(document.pointerLockElement===renderer.domElement)applyLook(e.movementX,e.movementY,.0021);});addEventListener('keydown',e=>keys.add(e.code));addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();resetJoystick();lookPointer=null;});}
function applyLook(dx,dy,sensitivity){yaw-=dx*sensitivity;pitch=clamp(pitch-dy*sensitivity,-1.42,1.42);yawRig.rotation.y=yaw;pitchRig.rotation.x=pitch;}
function movementInput(){let x=motion.x,y=-motion.y;if(keys.has('KeyW')||keys.has('ArrowUp'))y+=1;if(keys.has('KeyS')||keys.has('ArrowDown'))y-=1;if(keys.has('KeyD'))x+=1;if(keys.has('KeyA'))x-=1;const len=Math.hypot(x,y);if(len>1){x/=len;y/=len;}return{x,y};}
function updatePlayer(dt){const input=movementInput();if(!input.x&&!input.y)return;const speed=(keys.has('ShiftLeft')||keys.has('ShiftRight'))?RUN_SPEED:WALK_SPEED,sin=Math.sin(yaw),cos=Math.cos(yaw),dx=(input.x*cos-input.y*sin)*speed*dt,dz=(-input.x*sin-input.y*cos)*speed*dt,steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.18));for(let i=0;i<steps;i++){const sx=dx/steps,sz=dz/steps,nx=yawRig.position.x+sx,nz=yawRig.position.z+sz;if(canStand(nx,yawRig.position.z))yawRig.position.x=nx;if(canStand(yawRig.position.x,nz))yawRig.position.z=nz;}}
function animate(now){if(!started)return;const dt=Math.min(.033,(now-lastTime)/1000);lastTime=now;updatePlayer(dt);updateStreaming();if(localLight)localLight.intensity=baseLightIntensity*(.985+Math.sin(now*.008)*.015);coordsEl.textContent=`${Math.floor(yawRig.position.x)} , ${Math.floor(yawRig.position.z)}`;renderer.render(scene,camera);requestAnimationFrame(animate);}
startBtn.addEventListener('click',()=>{if(started)return;bootStatus.textContent='Generating higher-fidelity sectors…';startBtn.disabled=true;document.documentElement.requestFullscreen?.().catch?.(()=>{});try{initRenderer();installControls();started=true;startScreen.style.display='none';hud.classList.add('live');lastTime=performance.now();requestAnimationFrame(animate);}catch(err){console.error(err);bootStatus.textContent='Renderer failed to start. Reload and try again.';startBtn.disabled=false;}});
addEventListener('resize',()=>{if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});document.addEventListener('contextmenu',e=>e.preventDefault());
