import * as THREE from 'three';
import {CELL,GRID,CHUNK,WALL_H,cellIndex,hash2,mulberry32} from './world-v3.js';

const materialCache=new Map();
const sharedMaterials=new Set();
function mat(color,rough=.7,metal=0){const m=new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal});sharedMaterials.add(m);return m;}
const PROP_MATS={wood:mat(0x6c5c43,.82),darkWood:mat(0x4a4032,.86),metal:mat(0x858984,.42,.35),darkMetal:mat(0x4a4e4b,.46,.45),cream:mat(0xd6cfad,.8),chair:mat(0x625f50,.9),rust:mat(0x866246,.62,.22),whiteTile:mat(0xd8eeea,.36),pink:mat(0xe58aa8,.62),yellow:mat(0xe7c34f,.58),cyan:mat(0x70cbd1,.55),concrete:mat(0x666963,.95),green:mat(0x66856c,.9),soil:mat(0x49382c,1),leaf:mat(0x5a765b,.92),gallery:mat(0xc8c1b5,.82),mintMetal:mat(0x8ba99b,.55,.18),black:mat(0x242522,.6,.25),red:mat(0xb05a50,.62)};
function makeCanvasTexture(kind,theme){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d'),base=new THREE.Color(theme.wall);ctx.fillStyle=`#${base.getHexString()}`;ctx.fillRect(0,0,128,128);const rng=mulberry32(hash2(theme.wall,theme.floor,kind==='floor'?3:7));if(kind==='wall'){ctx.globalAlpha=.16;ctx.strokeStyle='#3a3525';for(let y=0;y<128;y+=16){ctx.beginPath();ctx.moveTo(0,y+rng()*3);ctx.lineTo(128,y+rng()*3);ctx.stroke();}for(let i=0;i<130;i++){ctx.globalAlpha=.035+rng()*.05;ctx.fillStyle=rng()>.5?'#fff':'#111';ctx.fillRect(rng()*128,rng()*128,1+rng()*2,3+rng()*10);}}else{ctx.fillStyle=`#${new THREE.Color(theme.floor).getHexString()}`;ctx.globalAlpha=1;ctx.fillRect(0,0,128,128);ctx.globalAlpha=.13;ctx.strokeStyle='#111';const step=theme.water?16:24;for(let i=0;i<=128;i+=step){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,128);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(128,i);ctx.stroke();}for(let i=0;i<90;i++){ctx.globalAlpha=.03+rng()*.05;ctx.fillStyle=rng()>.5?'#fff':'#000';ctx.fillRect(rng()*128,rng()*128,2+rng()*5,2+rng()*5);}}const tex=new THREE.CanvasTexture(c);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=2;return tex;}
function themeMaterials(theme){if(materialCache.has(theme.id))return materialCache.get(theme.id);const wallTex=makeCanvasTexture('wall',theme),floorTex=makeCanvasTexture('floor',theme);wallTex.repeat.set(1.5,1);floorTex.repeat.set(1,1);const mats={wall:new THREE.MeshStandardMaterial({map:wallTex,color:theme.wall,roughness:.94}),floor:new THREE.MeshStandardMaterial({map:floorTex,color:theme.floor,roughness:theme.water?.35:.96}),ceiling:new THREE.MeshStandardMaterial({color:theme.ceiling,roughness:.92}),panel:new THREE.MeshBasicMaterial({color:theme.light}),water:new THREE.MeshPhysicalMaterial({color:0x73dce8,transparent:true,opacity:.42,roughness:.08,transmission:.08,depthWrite:false})};Object.values(mats).forEach(m=>sharedMaterials.add(m));materialCache.set(theme.id,mats);return mats;}
function addInstances(group,geo,material,items){if(!items.length){geo.dispose();return;}const mesh=new THREE.InstancedMesh(geo,material,items.length),m=new THREE.Matrix4(),q=new THREE.Quaternion(),s=new THREE.Vector3(),p=new THREE.Vector3(),axis=new THREE.Vector3(0,1,0);items.forEach((v,i)=>{p.set(v[0],v[1],v[2]);q.setFromAxisAngle(axis,v[3]||0);s.set(v[4]??1,v[5]??1,v[6]??1);m.compose(p,q,s);mesh.setMatrixAt(i,m);});mesh.instanceMatrix.needsUpdate=true;group.add(mesh);}
function addBox(group,material,items){addInstances(group,new THREE.BoxGeometry(1,1,1),material,items.map(v=>[v.x,v.y,v.z,v.rot||0,v.w,v.h,v.d]));}
function boundaryOpen(data,x,z,nx,nz){if(nz<0)return x===data.gates.N;if(nz>=GRID)return x===data.gates.S;if(nx<0)return z===data.gates.W;if(nx>=GRID)return z===data.gates.E;return false;}

export function buildChunk(scene,data){const {cx,cz,grid,theme}=data,group=new THREE.Group();group.position.set(cx*CHUNK,0,cz*CHUNK);group.userData.theme=theme;const mats=themeMaterials(theme),floors=[],ceilings=[],walls=[],roomHeight=theme.tall?5.4:WALL_H;for(let z=0;z<GRID;z++)for(let x=0;x<GRID;x++){if(!grid[cellIndex(x,z)])continue;const px=(x+.5)*CELL,pz=(z+.5)*CELL;floors.push([px,0,pz,0]);ceilings.push([px,roomHeight,pz,0]);const n=(nx,nz)=>nx>=0&&nz>=0&&nx<GRID&&nz<GRID?grid[cellIndex(nx,nz)]:boundaryOpen(data,x,z,nx,nz);if(!n(x,z-1))walls.push([px,roomHeight/2,pz-CELL/2,0]);if(!n(x,z+1))walls.push([px,roomHeight/2,pz+CELL/2,0]);if(!n(x-1,z))walls.push([px-CELL/2,roomHeight/2,pz,Math.PI/2]);if(!n(x+1,z))walls.push([px+CELL/2,roomHeight/2,pz,Math.PI/2]);}addInstances(group,new THREE.BoxGeometry(CELL,.12,CELL),mats.floor,floors);addInstances(group,new THREE.BoxGeometry(CELL,.1,CELL),mats.ceiling,ceilings);addInstances(group,new THREE.BoxGeometry(CELL+.06,roomHeight,.14),mats.wall,walls);const rng=mulberry32(data.decorSeed^0x55aa55),panels=[];for(let z=1;z<GRID-1;z+=2)for(let x=1;x<GRID-1;x+=2)if(grid[cellIndex(x,z)]&&rng()>.32)panels.push([(x+.5)*CELL,roomHeight-.08,(z+.5)*CELL,rng()>.5?0:Math.PI/2]);addInstances(group,new THREE.BoxGeometry(2.25,.045,.34),mats.panel,panels);addDoorFrames(group,data);addDecor(group,data,mats,roomHeight);scene.add(group);return group;}
function addDoorFrames(group,data){const f=[],post=.18,span=2.7,topY=2.55,push=(x,z,side)=>{if(side==='NS')f.push({x:x-1.25,z,y:1.25,w:post,h:2.5,d:post},{x:x+1.25,z,y:1.25,w:post,h:2.5,d:post},{x,z,y:topY,w:span,h:.18,d:post});else f.push({x,z:z-1.25,y:1.25,w:post,h:2.5,d:post},{x,z:z+1.25,y:1.25,w:post,h:2.5,d:post},{x,z,y:topY,w:post,h:.18,d:span});};push((data.gates.N+.5)*CELL,.18,'NS');push((data.gates.S+.5)*CELL,CHUNK-.18,'NS');push(.18,(data.gates.W+.5)*CELL,'EW');push(CHUNK-.18,(data.gates.E+.5)*CELL,'EW');addBox(group,PROP_MATS.darkMetal,f);}
function addDecor(group,data,mats,roomHeight){const p=data.decor,byType={};for(const b of p.boxes)(byType[b.type]??=[]).push(b);const add=(type,material)=>{if(byType[type])addBox(group,material,byType[type]);};add('desk',PROP_MATS.darkWood);add('cabinet',PROP_MATS.cream);add('chair',PROP_MATS.chair);add('poolBench',PROP_MATS.whiteTile);add('towelCart',PROP_MATS.metal);add('foamBlock',PROP_MATS.yellow);add('playBench',PROP_MATS.pink);add('machine',PROP_MATS.darkMetal);add('locker',PROP_MATS.metal);add('crate',PROP_MATS.wood);add('galleryBench',PROP_MATS.gallery);add('planter',PROP_MATS.concrete);add('plinth',PROP_MATS.gallery);add('mintBench',PROP_MATS.mintMetal);add('utilityCart',PROP_MATS.metal);add('cabinetMint',PROP_MATS.mintMetal);if(byType.desk)addDeskDetails(group,byType.desk);if(byType.chair)addChairDetails(group,byType.chair);if(byType.machine)addMachineDetails(group,byType.machine);if(byType.locker)addLockerDetails(group,byType.locker);if(byType.crate)addCrateDetails(group,byType.crate);if(byType.planter)addPlanterDetails(group,byType.planter);if(byType.utilityCart)addCartDetails(group,byType.utilityCart);addFloorDetails(group,p);addCylinderDetails(group,p);addSigns(group,data,p);if(p.slides.length)addSlides(group,p.slides);if(p.pools.length)addPools(group,p.pools,mats);}
function addDeskDetails(group,items){const legs=[];for(const b of items)for(const sx of[-.82,.82])for(const sz of[-.35,.35])legs.push({x:b.x+sx,z:b.z+sz,y:.37,w:.09,d:.09,h:.74});addBox(group,PROP_MATS.black,legs);}
function addChairDetails(group,items){addBox(group,PROP_MATS.chair,items.map(b=>({x:b.x,z:b.z+(b.rot?0:.25),y:.72,w:b.rot?.12:.62,d:b.rot?.62:.12,h:.82})));}
function addMachineDetails(group,items){addBox(group,PROP_MATS.black,items.map(b=>({x:b.x,z:b.z-.64,y:1.05,w:1.18,d:.04,h:.62,rot:b.rot})));addBox(group,PROP_MATS.red,items.map(b=>({x:b.x-.38,z:b.z-.67,y:1.18,w:.12,d:.04,h:.12,rot:b.rot})));}
function addLockerDetails(group,items){const seams=[];for(const b of items)seams.push({x:b.x,z:b.z-.285,y:1,w:.55,d:.025,h:.025,rot:b.rot},{x:b.x,z:b.z-.285,y:1.5,w:.55,d:.025,h:.025,rot:b.rot});addBox(group,PROP_MATS.darkMetal,seams);}
function addCrateDetails(group,items){const straps=[];for(const b of items)straps.push({x:b.x,z:b.z,y:b.h+.02,w:b.w*.9,d:.09,h:.05},{x:b.x,z:b.z,y:b.h+.02,w:.09,d:b.d*.9,h:.05});addBox(group,PROP_MATS.darkMetal,straps);}
function addPlanterDetails(group,items){addBox(group,PROP_MATS.soil,items.map(b=>({x:b.x,z:b.z,y:b.h+.02,w:b.w*.82,d:b.d*.82,h:.08})));const stems=[],leaves=[];for(const b of items){stems.push([b.x,b.h+.55,b.z,0,.12,.9,.12]);for(let i=0;i<5;i++){const a=i/5*Math.PI*2;leaves.push([b.x+Math.cos(a)*.28,b.h+.75+(i%2)*.18,b.z+Math.sin(a)*.28,a,.34,.5,.12]);}}addInstances(group,new THREE.BoxGeometry(1,1,1),PROP_MATS.green,stems);addInstances(group,new THREE.SphereGeometry(.5,6,5),PROP_MATS.leaf,leaves);}
function addCartDetails(group,items){const rails=[];for(const b of items)rails.push({x:b.x,z:b.z,y:.62,w:b.w*.9,d:.08,h:.06},{x:b.x,z:b.z,y:.25,w:b.w*.9,d:.08,h:.06});addBox(group,PROP_MATS.darkMetal,rails);}
function addFloorDetails(group,p){const stains=p.planes.filter(x=>x.type==='stain'),drains=p.planes.filter(x=>x.type==='drain');if(stains.length){const m=new THREE.MeshBasicMaterial({color:0x564b2e,transparent:true,opacity:.3,depthWrite:false});addInstances(group,new THREE.PlaneGeometry(1,1).rotateX(-Math.PI/2),m,stains.map(v=>[v.x,v.y,v.z,v.rot,v.w,1,v.d]));}if(drains.length){const m=new THREE.MeshStandardMaterial({color:0x4b6264,roughness:.3,metalness:.65});addInstances(group,new THREE.CircleGeometry(.5,12).rotateX(-Math.PI/2),m,drains.map(v=>[v.x,v.y,v.z,0,v.w,1,v.d]));}}
function addCylinderDetails(group,p){const ladders=p.cylinders.filter(x=>x.type==='ladder'),tunnels=p.cylinders.filter(x=>x.type==='tunnel'),pipes=p.cylinders.filter(x=>x.type==='pipe');if(ladders.length)for(const l of ladders){const g=new THREE.Group();g.position.set(l.x,0,l.z);g.rotation.y=l.rot;const bars=[{x:-.42,y:.82,z:0,w:.11,h:1.65,d:.11},{x:.42,y:.82,z:0,w:.11,h:1.65,d:.11}];for(let y=.2;y<1.5;y+=.27)bars.push({x:0,y,z:0,w:.84,h:.09,d:.09});addBox(g,PROP_MATS.metal,bars);group.add(g);}if(tunnels.length)for(const t of tunnels){const geo=new THREE.TorusGeometry(t.r,.12,8,18),root=new THREE.Group();root.position.set(t.x,t.y,t.z);root.rotation.y=t.rot;for(let off=-.6;off<=.6;off+=.6){const ring=new THREE.Mesh(geo,PROP_MATS.cyan);ring.position.z=off;root.add(ring);}group.add(root);}if(pipes.length)addInstances(group,new THREE.CylinderGeometry(.5,.5,1,8).rotateZ(Math.PI/2),PROP_MATS.rust,pipes.map(v=>[v.x,v.y,v.z,v.rot,v.r*2,v.h,v.r*2]));}
function addSigns(group,data,p){for(let i=0;i<p.signs.length;i++){const s=p.signs[i],c=document.createElement('canvas');c.width=256;c.height=128;const ctx=c.getContext('2d');if(s.type==='art'){const hue=hash2(data.cx+i,data.cz,0x8888)%360;ctx.fillStyle=`hsl(${hue} 24% 30%)`;ctx.fillRect(0,0,256,128);ctx.fillStyle='rgba(235,228,211,.72)';for(let k=0;k<8;k++)ctx.fillRect(18+k*28,18+(k%3)*22,18,56-(k%2)*12);}else{ctx.fillStyle='#232522';ctx.fillRect(0,0,256,128);ctx.fillStyle='#d9d4b8';ctx.font='bold 44px monospace';ctx.textAlign='center';ctx.textBaseline='middle';const code=(hash2(data.cx+i,data.cz,0x7777)%900)+100;ctx.fillText(`${String.fromCharCode(65+(code%6))}-${code}`,128,64);}const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const material=new THREE.MeshStandardMaterial({map:tex,roughness:.68,emissive:0x111111}),mesh=new THREE.Mesh(new THREE.BoxGeometry(s.type==='art'?1.7:1.25,s.type==='art'?1.05:.62,.055),material);mesh.position.set(s.x,s.y,s.z);mesh.rotation.y=s.rot;group.add(mesh);}}
function addSlides(group,slides){for(const s of slides){const root=new THREE.Group();root.position.set(s.x,0,s.z);root.rotation.y=s.rot;const points=[new THREE.Vector3(-1.3,2.55,-1),new THREE.Vector3(-.4,2.2,-.3),new THREE.Vector3(.6,1.4,.4),new THREE.Vector3(1.35,.48,1.05)],curve=new THREE.CatmullRomCurve3(points);root.add(new THREE.Mesh(new THREE.TubeGeometry(curve,24,.38,8,false),PROP_MATS.pink));const platform=new THREE.Mesh(new THREE.BoxGeometry(1.9,.18,1.9),PROP_MATS.yellow);platform.position.set(-1.3,2.5,-1);root.add(platform);const poles=[];for(const x of[-1.9,-.7])for(const z of[-1.6,-.4])poles.push([x,1.25,z,0,.11,2.5,.11]);addInstances(root,new THREE.CylinderGeometry(.5,.5,1,8),PROP_MATS.cyan,poles);group.add(root);}}
function addPools(group,pools,mats){for(const p of pools){const water=new THREE.Mesh(new THREE.PlaneGeometry(p.w,p.d).rotateX(-Math.PI/2),mats.water);water.position.set(p.x,.1,p.z);group.add(water);addBox(group,PROP_MATS.whiteTile,[{x:p.x,z:p.z-p.d/2,y:.17,w:p.w+.28,d:.18,h:.22},{x:p.x,z:p.z+p.d/2,y:.17,w:p.w+.28,d:.18,h:.22},{x:p.x-p.w/2,z:p.z,y:.17,w:.18,d:p.d,h:.22},{x:p.x+p.w/2,z:p.z,y:.17,w:.18,d:p.d,h:.22}]);}}
export function disposeChunkGroup(group){const seen=new Set();group.traverse(o=>{if(o.geometry)o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if(!m||sharedMaterials.has(m)||seen.has(m))continue;seen.add(m);if(m.map)m.map.dispose();if(m.emissiveMap)m.emissiveMap.dispose();m.dispose();}});}
