import * as THREE from 'three';
import {CELL,GRID,CHUNK,WALL_H,cellIndex,hash2,mulberry32} from './world-v4.js';

const materialCache=new Map();
const sharedMaterials=new Set();
function mat(color,rough=.7,metal=0){const m=new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal});sharedMaterials.add(m);return m;}
const PROP_MATS={wood:mat(0x6d5d47,.84),darkWood:mat(0x4e4437,.88),metal:mat(0x8b908b,.44,.32),darkMetal:mat(0x4b504d,.48,.38),cream:mat(0xb7b08f,.88),chair:mat(0x5f604f,.9),rust:mat(0x82634a,.65,.2),whiteTile:mat(0xdbece8,.34),pink:mat(0xd9809c,.6),yellow:mat(0xddbe50,.58),cyan:mat(0x70c4cb,.5),concrete:mat(0x74756d,.94),green:mat(0x657c62,.9),soil:mat(0x49382c,1),leaf:mat(0x60785e,.92),gallery:mat(0xc6c0b5,.82),mintMetal:mat(0x86a99a,.58,.15),black:mat(0x252723,.62,.22),red:mat(0xa55048,.64),trim:mat(0x7c7350,.92),rubber:mat(0x353632,.96)};

function speckle(ctx,rng,count,light='#fff',dark='#000',alpha=.055){for(let i=0;i<count;i++){ctx.globalAlpha=alpha*(.35+rng());ctx.fillStyle=rng()>.5?light:dark;const s=.6+rng()*2.2;ctx.fillRect(rng()*ctx.canvas.width,rng()*ctx.canvas.height,s,s);}}
function blotch(ctx,rng,color,alpha=.08){const x=rng()*256,y=rng()*256,r=14+rng()*35,g=ctx.createRadialGradient(x,y,1,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'rgba(0,0,0,0)');ctx.globalAlpha=alpha;ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function makeSurfaceTexture(kind,theme){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d'),rng=mulberry32(hash2(theme.wall,theme.floor,(kind==='floor'?3:kind==='ceiling'?11:7)));const base=new THREE.Color(kind==='floor'?theme.floor:kind==='ceiling'?theme.ceiling:theme.wall);ctx.globalAlpha=1;ctx.fillStyle=`#${base.getHexString()}`;ctx.fillRect(0,0,256,256);
 if(kind==='wall'){
  if(theme.id==='classic'){ctx.strokeStyle='rgba(83,74,43,.16)';ctx.lineWidth=1;for(let x=0;x<=256;x+=64){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,256);ctx.stroke();}for(let y=20;y<256;y+=36){ctx.globalAlpha=.045;ctx.strokeStyle='#403b29';ctx.beginPath();ctx.moveTo(0,y+rng()*2);ctx.lineTo(256,y+rng()*2);ctx.stroke();}for(let i=0;i<5;i++)blotch(ctx,rng,'rgba(92,78,38,.7)',.08);speckle(ctx,rng,420,'#fff','#403b25',.045);
  }else if(theme.id==='pool'){ctx.strokeStyle='rgba(86,132,132,.25)';ctx.lineWidth=2;for(let i=0;i<=256;i+=32){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,256);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(256,i);ctx.stroke();}speckle(ctx,rng,180,'#fff','#5d8080',.035);
  }else if(theme.id==='service'){speckle(ctx,rng,720,'#c4c8c3','#1f211f',.07);for(let i=0;i<8;i++){ctx.globalAlpha=.14;ctx.strokeStyle='#222522';ctx.beginPath();let x=rng()*256,y=rng()*256;ctx.moveTo(x,y);for(let k=0;k<4;k++){x+=-18+rng()*36;y+=8+rng()*24;ctx.lineTo(x,y);}ctx.stroke();}}
  else{speckle(ctx,rng,360,'#fff','#555',.035);}
 }else if(kind==='floor'){
  if(theme.id==='classic'){for(let i=0;i<1500;i++){ctx.globalAlpha=.035+rng()*.09;ctx.strokeStyle=rng()>.5?'#d2c59a':'#554c35';const x=rng()*256,y=rng()*256;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-1+rng()*3,y+1+rng()*3);ctx.stroke();}for(let i=0;i<7;i++)blotch(ctx,rng,'rgba(62,50,27,.85)',.1);
  }else if(theme.id==='pool'){ctx.strokeStyle='rgba(48,105,109,.28)';ctx.lineWidth=2;for(let i=0;i<=256;i+=32){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,256);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(256,i);ctx.stroke();}speckle(ctx,rng,220,'#fff','#477477',.045);
  }else if(theme.id==='service'){speckle(ctx,rng,900,'#aaa','#171817',.075);for(let i=0;i<6;i++)blotch(ctx,rng,'rgba(28,29,27,.8)',.1);
  }else{ctx.strokeStyle='rgba(45,55,50,.09)';for(let i=0;i<=256;i+=64){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,256);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(256,i);ctx.stroke();}speckle(ctx,rng,360,'#fff','#444',.035);}
 }else{
  ctx.strokeStyle=theme.id==='service'?'rgba(20,22,20,.3)':'rgba(84,83,67,.18)';ctx.lineWidth=1.5;for(let i=0;i<=256;i+=64){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,256);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(256,i);ctx.stroke();}speckle(ctx,rng,260,'#fff','#555',.03);if(theme.id==='classic')for(let i=0;i<3;i++)blotch(ctx,rng,'rgba(104,92,54,.55)',.055);
 }
 ctx.globalAlpha=1;const tex=new THREE.CanvasTexture(c);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=4;return tex;}
function themeMaterials(theme){if(materialCache.has(theme.id))return materialCache.get(theme.id);const wallTex=makeSurfaceTexture('wall',theme),floorTex=makeSurfaceTexture('floor',theme),ceilingTex=makeSurfaceTexture('ceiling',theme);const mats={wall:new THREE.MeshStandardMaterial({map:wallTex,color:0xffffff,roughness:.96}),floor:new THREE.MeshStandardMaterial({map:floorTex,color:0xffffff,roughness:theme.water?.38:.98}),ceiling:new THREE.MeshStandardMaterial({map:ceilingTex,color:0xffffff,roughness:.94}),panel:new THREE.MeshStandardMaterial({color:0xfff5cc,emissive:theme.light,emissiveIntensity:2.4,roughness:.45}),housing:new THREE.MeshStandardMaterial({color:theme.id==='service'?0x444743:0x9a9885,roughness:.72,metalness:.12}),water:new THREE.MeshPhysicalMaterial({color:0x76d5df,transparent:true,opacity:.42,roughness:.06,metalness:0,transmission:.1,depthWrite:false})};Object.values(mats).forEach(m=>sharedMaterials.add(m));materialCache.set(theme.id,mats);return mats;}
function addInstances(group,geo,material,items){if(!items.length){geo.dispose();return;}const mesh=new THREE.InstancedMesh(geo,material,items.length),m=new THREE.Matrix4(),q=new THREE.Quaternion(),s=new THREE.Vector3(),p=new THREE.Vector3(),axis=new THREE.Vector3(0,1,0);items.forEach((v,i)=>{p.set(v[0],v[1],v[2]);q.setFromAxisAngle(axis,v[3]||0);s.set(v[4]??1,v[5]??1,v[6]??1);m.compose(p,q,s);mesh.setMatrixAt(i,m);});mesh.instanceMatrix.needsUpdate=true;group.add(mesh);}
function addBox(group,material,items){if(!items?.length)return;addInstances(group,new THREE.BoxGeometry(1,1,1),material,items.map(v=>[v.x,v.y,v.z,v.rot||0,v.w,v.h,v.d]));}
function boundaryOpen(data,x,z,nx,nz){if(nz<0)return x===data.gates.N;if(nz>=GRID)return x===data.gates.S;if(nx<0)return z===data.gates.W;if(nx>=GRID)return z===data.gates.E;return false;}
function roomHeight(theme){if(theme.id==='classic')return 2.85;if(theme.id==='service')return 3.05;if(theme.tall)return 5.2;return 3.2;}

export function buildChunk(scene,data){const {cx,cz,grid,theme}=data,group=new THREE.Group();group.position.set(cx*CHUNK,0,cz*CHUNK);group.userData.theme=theme;const mats=themeMaterials(theme),floors=[],ceilings=[],walls=[],skirting=[],h=roomHeight(theme);for(let z=0;z<GRID;z++)for(let x=0;x<GRID;x++){if(!grid[cellIndex(x,z)])continue;const px=(x+.5)*CELL,pz=(z+.5)*CELL;floors.push([px,0,pz,0]);ceilings.push([px,h,pz,0]);const n=(nx,nz)=>nx>=0&&nz>=0&&nx<GRID&&nz<GRID?grid[cellIndex(nx,nz)]:boundaryOpen(data,x,z,nx,nz),pushWall=(xx,zz,r)=>{walls.push([xx,h/2,zz,r]);if(theme.id==='classic')skirting.push([xx,.08,zz,r]);};if(!n(x,z-1))pushWall(px,pz-CELL/2,0);if(!n(x,z+1))pushWall(px,pz+CELL/2,0);if(!n(x-1,z))pushWall(px-CELL/2,pz,Math.PI/2);if(!n(x+1,z))pushWall(px+CELL/2,pz,Math.PI/2);}
 addInstances(group,new THREE.BoxGeometry(CELL,.12,CELL),mats.floor,floors);addInstances(group,new THREE.BoxGeometry(CELL,.09,CELL),mats.ceiling,ceilings);addInstances(group,new THREE.BoxGeometry(CELL+.06,h,.14),mats.wall,walls);if(skirting.length)addInstances(group,new THREE.BoxGeometry(CELL+.08,.16,.19),PROP_MATS.trim,skirting);
 const rng=mulberry32(data.decorSeed^0x55aa55),panels=[];for(let z=1;z<GRID-1;z+=2)for(let x=1;x<GRID-1;x+=2)if(grid[cellIndex(x,z)]&&rng()>.26)panels.push([(x+.5)*CELL,h-.075,(z+.5)*CELL,rng()>.5?0:Math.PI/2]);addInstances(group,new THREE.BoxGeometry(2.35,.055,.48),mats.housing,panels);addInstances(group,new THREE.BoxGeometry(2.02,.025,.26),mats.panel,panels.map(v=>[v[0],h-.11,v[2],v[3]]));addDoorFrames(group,data,h);addDecor(group,data,mats,h);scene.add(group);return group;}
function addDoorFrames(group,data,h){const f=[],post=.15,span=2.55,topY=Math.min(2.42,h-.26),push=(x,z,side)=>{if(side==='NS')f.push({x:x-1.18,z,y:topY/2,w:post,h:topY,d:post},{x:x+1.18,z,y:topY/2,w:post,h:topY,d:post},{x,z,y:topY,w:span,h:.15,d:post});else f.push({x,z:z-1.18,y:topY/2,w:post,h:topY,d:post},{x,z:z+1.18,y:topY/2,w:post,h:topY,d:post},{x,z,y:topY,w:post,h:.15,d:span});};push((data.gates.N+.5)*CELL,.16,'NS');push((data.gates.S+.5)*CELL,CHUNK-.16,'NS');push(.16,(data.gates.W+.5)*CELL,'EW');push(CHUNK-.16,(data.gates.E+.5)*CELL,'EW');addBox(group,PROP_MATS.darkMetal,f);}
function byType(boxes){const o={};for(const b of boxes)(o[b.type]??=[]).push(b);return o;}
function addDecor(group,data,mats,h){const p=data.decor,b=byType(p.boxes),generic=(type,material)=>{if(b[type])addBox(group,material,b[type]);};if(b.partition)addBox(group,mats.wall,b.partition);if(b.desk)addDesks(group,b.desk);if(b.cabinet)addCabinets(group,b.cabinet);if(b.chair)addChairs(group,b.chair);if(b.pillar)addPillars(group,b.pillar);generic('poolBench',PROP_MATS.whiteTile);generic('towelCart',PROP_MATS.metal);generic('foamBlock',PROP_MATS.yellow);generic('playBench',PROP_MATS.pink);generic('machine',PROP_MATS.darkMetal);generic('locker',PROP_MATS.metal);generic('crate',PROP_MATS.wood);generic('galleryBench',PROP_MATS.gallery);generic('planter',PROP_MATS.concrete);generic('plinth',PROP_MATS.gallery);generic('mintBench',PROP_MATS.mintMetal);generic('utilityCart',PROP_MATS.metal);generic('cabinetMint',PROP_MATS.mintMetal);if(b.machine)addMachineDetails(group,b.machine);if(b.locker)addLockerDetails(group,b.locker);if(b.crate)addCrateDetails(group,b.crate);if(b.planter)addPlanterDetails(group,b.planter);if(b.utilityCart)addCartDetails(group,b.utilityCart);addFloorDetails(group,p);addCylinderDetails(group,p);addSigns(group,data,p);addCeilingDetails(group,p,h);if(p.slides.length)addSlides(group,p.slides);if(p.pools.length)addPools(group,p.pools,mats);}
function rootFor(group,b){const r=new THREE.Group();r.position.set(b.x,0,b.z);r.rotation.y=b.rot||0;group.add(r);return r;}
function addDesks(group,items){for(const b of items){const r=rootFor(group,b);addBox(r,PROP_MATS.darkWood,[{x:0,z:0,y:.75,w:2.05,d:1,h:.11},{x:-.75,z:0,y:.39,w:.42,d:.84,h:.7}]);const legs=[];for(const x of[-.91,.91])for(const z of[-.41,.41])legs.push({x,z,y:.36,w:.075,d:.075,h:.72});addBox(r,PROP_MATS.black,legs);addBox(r,PROP_MATS.metal,[{x:-.75,z:-.43,y:.54,w:.24,d:.025,h:.045},{x:-.75,z:-.43,y:.34,w:.24,d:.025,h:.045}]);}}
function addChairs(group,items){for(const b of items){const r=rootFor(group,b);addBox(r,PROP_MATS.chair,[{x:0,z:0,y:.48,w:.62,d:.62,h:.12},{x:0,z:.27,y:.83,w:.62,d:.11,h:.7}]);const legs=[];for(const x of[-.24,.24])for(const z of[-.24,.24])legs.push({x,z,y:.23,w:.055,d:.055,h:.46});addBox(r,PROP_MATS.black,legs);}}
function addCabinets(group,items){for(const b of items){const r=rootFor(group,b);addBox(r,PROP_MATS.cream,[{x:0,z:0,y:.775,w:.72,d:.58,h:1.55}]);const lines=[],handles=[];for(let i=1;i<4;i++)lines.push({x:0,z:-.296,y:i*.37,w:.62,d:.018,h:.018});for(let i=0;i<4;i++)handles.push({x:0,z:-.31,y:.19+i*.37,w:.16,d:.025,h:.035});addBox(r,PROP_MATS.darkMetal,lines);addBox(r,PROP_MATS.metal,handles);}}
function addPillars(group,items){for(const b of items){const r=rootFor(group,b);addBox(r,PROP_MATS.cream,[{x:0,z:0,y:1.34,w:.44,d:.44,h:2.68},{x:0,z:0,y:.08,w:.68,d:.68,h:.16},{x:0,z:0,y:2.6,w:.64,d:.64,h:.14}]);}}
function addMachineDetails(group,items){addBox(group,PROP_MATS.black,items.map(b=>({x:b.x,z:b.z-.64,y:1.05,w:1.18,d:.04,h:.62,rot:b.rot})));addBox(group,PROP_MATS.red,items.map(b=>({x:b.x-.38,z:b.z-.67,y:1.18,w:.12,d:.04,h:.12,rot:b.rot})));}
function addLockerDetails(group,items){const seams=[];for(const b of items)seams.push({x:b.x,z:b.z-.285,y:1,w:.55,d:.025,h:.025,rot:b.rot},{x:b.x,z:b.z-.285,y:1.5,w:.55,d:.025,h:.025,rot:b.rot});addBox(group,PROP_MATS.darkMetal,seams);}
function addCrateDetails(group,items){const straps=[];for(const b of items)straps.push({x:b.x,z:b.z,y:b.h+.02,w:b.w*.9,d:.09,h:.05},{x:b.x,z:b.z,y:b.h+.02,w:.09,d:b.d*.9,h:.05});addBox(group,PROP_MATS.darkMetal,straps);}
function addPlanterDetails(group,items){addBox(group,PROP_MATS.soil,items.map(b=>({x:b.x,z:b.z,y:b.h+.02,w:b.w*.82,d:b.d*.82,h:.08})));const stems=[],leaves=[];for(const b of items){stems.push([b.x,b.h+.55,b.z,0,.12,.9,.12]);for(let i=0;i<5;i++){const a=i/5*Math.PI*2;leaves.push([b.x+Math.cos(a)*.28,b.h+.75+(i%2)*.18,b.z+Math.sin(a)*.28,a,.34,.5,.12]);}}addInstances(group,new THREE.BoxGeometry(1,1,1),PROP_MATS.green,stems);addInstances(group,new THREE.SphereGeometry(.5,6,5),PROP_MATS.leaf,leaves);}
function addCartDetails(group,items){const rails=[];for(const b of items)rails.push({x:b.x,z:b.z,y:.62,w:b.w*.9,d:.08,h:.06},{x:b.x,z:b.z,y:.25,w:b.w*.9,d:.08,h:.06});addBox(group,PROP_MATS.darkMetal,rails);}
function addFloorDetails(group,p){const stains=p.planes.filter(x=>x.type==='stain'),drains=p.planes.filter(x=>x.type==='drain');if(stains.length){const m=new THREE.MeshBasicMaterial({color:0x4d422e,transparent:true,opacity:.16,depthWrite:false});addInstances(group,new THREE.PlaneGeometry(1,1).rotateX(-Math.PI/2),m,stains.map(v=>[v.x,v.y,v.z,v.rot,v.w,1,v.d]));}if(drains.length){const m=new THREE.MeshStandardMaterial({color:0x4b6264,roughness:.3,metalness:.65});addInstances(group,new THREE.CircleGeometry(.5,12).rotateX(-Math.PI/2),m,drains.map(v=>[v.x,v.y,v.z,0,v.w,1,v.d]));}}
function addCylinderDetails(group,p){const ladders=p.cylinders.filter(x=>x.type==='ladder'),tunnels=p.cylinders.filter(x=>x.type==='tunnel'),pipes=p.cylinders.filter(x=>x.type==='pipe');if(ladders.length)for(const l of ladders){const g=new THREE.Group();g.position.set(l.x,0,l.z);g.rotation.y=l.rot;const bars=[{x:-.42,y:.82,z:0,w:.11,h:1.65,d:.11},{x:.42,y:.82,z:0,w:.11,h:1.65,d:.11}];for(let y=.2;y<1.5;y+=.27)bars.push({x:0,y,z:0,w:.84,h:.09,d:.09});addBox(g,PROP_MATS.metal,bars);group.add(g);}if(tunnels.length)for(const t of tunnels){const geo=new THREE.TorusGeometry(t.r,.12,8,18),root=new THREE.Group();root.position.set(t.x,t.y,t.z);root.rotation.y=t.rot;for(let off=-.6;off<=.6;off+=.6){const ring=new THREE.Mesh(geo,PROP_MATS.cyan);ring.position.z=off;root.add(ring);}group.add(root);}if(pipes.length)addInstances(group,new THREE.CylinderGeometry(.5,.5,1,8).rotateZ(Math.PI/2),PROP_MATS.rust,pipes.map(v=>[v.x,v.y,v.z,v.rot,v.r*2,v.h,v.r*2]));}
function addCeilingDetails(group,p,h){const vents=p.ceiling?.filter(x=>x.type==='vent')||[];if(!vents.length)return;const ventMat=new THREE.MeshStandardMaterial({color:0x4e5049,roughness:.48,metalness:.4}),slots=[];for(const v of vents){const r=new THREE.Group();r.position.set(v.x,h-.075,v.z);r.rotation.y=v.rot;const plate=new THREE.Mesh(new THREE.BoxGeometry(1.05,.035,.68),ventMat);r.add(plate);for(let i=-3;i<=3;i++)slots.push({root:r,x:i*.12});group.add(r);}for(const s of slots)addBox(s.root,PROP_MATS.black,[{x:s.x,z:0,y:-.022,w:.035,d:.5,h:.018}]);}
function addSigns(group,data,p){for(let i=0;i<p.signs.length;i++){const s=p.signs[i],c=document.createElement('canvas');c.width=256;c.height=128;const ctx=c.getContext('2d');ctx.clearRect(0,0,256,128);let w=1.25,h=.62;if(s.type==='art'){w=1.7;h=1.05;const hue=hash2(data.cx+i,data.cz,0x8888)%360;ctx.fillStyle=`hsl(${hue} 20% 31%)`;ctx.fillRect(0,0,256,128);ctx.fillStyle='rgba(235,228,211,.72)';for(let k=0;k<8;k++)ctx.fillRect(18+k*28,18+(k%3)*22,18,56-(k%2)*12);}else if(s.type==='grime'){w=1.45;h=.9;for(let k=0;k<18;k++){const x=30+Math.random()*196,y=15+Math.random()*98,r=6+Math.random()*26,g=ctx.createRadialGradient(x,y,1,x,y,r);g.addColorStop(0,'rgba(72,60,29,.24)');g.addColorStop(1,'rgba(72,60,29,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}}else{ctx.fillStyle='#2a2b27';ctx.fillRect(0,0,256,128);ctx.fillStyle='#ddd7ba';ctx.font='bold 44px monospace';ctx.textAlign='center';ctx.textBaseline='middle';const code=(hash2(data.cx+i,data.cz,0x7777)%900)+100;ctx.fillText(`${String.fromCharCode(65+(code%6))}-${code}`,128,64);}const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const material=s.type==='grime'?new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,side:THREE.DoubleSide}):new THREE.MeshStandardMaterial({map:tex,roughness:.7,emissive:0x080808}),mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),material);mesh.position.set(s.x,s.y,s.z);mesh.rotation.y=s.rot;group.add(mesh);}}
function addSlides(group,slides){for(const s of slides){const root=new THREE.Group();root.position.set(s.x,0,s.z);root.rotation.y=s.rot;const points=[new THREE.Vector3(-1.3,2.55,-1),new THREE.Vector3(-.4,2.2,-.3),new THREE.Vector3(.6,1.4,.4),new THREE.Vector3(1.35,.48,1.05)],curve=new THREE.CatmullRomCurve3(points);root.add(new THREE.Mesh(new THREE.TubeGeometry(curve,24,.38,8,false),PROP_MATS.pink));const platform=new THREE.Mesh(new THREE.BoxGeometry(1.9,.18,1.9),PROP_MATS.yellow);platform.position.set(-1.3,2.5,-1);root.add(platform);const poles=[];for(const x of[-1.9,-.7])for(const z of[-1.6,-.4])poles.push([x,1.25,z,0,.11,2.5,.11]);addInstances(root,new THREE.CylinderGeometry(.5,.5,1,8),PROP_MATS.cyan,poles);group.add(root);}}
function addPools(group,pools,mats){for(const p of pools){const water=new THREE.Mesh(new THREE.PlaneGeometry(p.w,p.d).rotateX(-Math.PI/2),mats.water);water.position.set(p.x,.1,p.z);group.add(water);addBox(group,PROP_MATS.whiteTile,[{x:p.x,z:p.z-p.d/2,y:.17,w:p.w+.28,d:.18,h:.22},{x:p.x,z:p.z+p.d/2,y:.17,w:p.w+.28,d:.18,h:.22},{x:p.x-p.w/2,z:p.z,y:.17,w:.18,d:p.d,h:.22},{x:p.x+p.w/2,z:p.z,y:.17,w:.18,d:p.d,h:.22}]);}}
export function disposeChunkGroup(group){const seen=new Set();group.traverse(o=>{if(o.geometry)o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if(!m||sharedMaterials.has(m)||seen.has(m))continue;seen.add(m);if(m.map)m.map.dispose();if(m.emissiveMap)m.emissiveMap.dispose();m.dispose();}});}
