export { GAME_CONFIG } from "./config.js";
export { ZONES, getEnabledZones } from "./zones.js";
export { ASSETS, REALISM_TARGETS, WORLD_REGIONS } from "./assets/manifest.js";
export { setupRenderer } from "./renderer.js";
export { setupWorld } from "./world.js";
export { createTerrain } from "./terrain.js";
export { updateChunks } from "./chunks.js";
export { createTrees } from "./trees.js";
export { setupPlayer } from "./player.js";
export { setupControls } from "./controls.js";
export { setupGameUI } from "./game-ui.js";
export { setupRoads } from "./roads.js";
export { setupVehicles } from "./vehicles.js";
export { setupCities } from "./cities.js";
export { setupIndoorAreas } from "./indoor-areas.js";
export { setupPortals } from "./portals.js";
export { setupDimensions } from "./dimensions.js";
export { setupEvents } from "./events.js";
export { setupNPCs } from "./npcs.js";
export { setupAnimals } from "./animals.js";
export { setupCombat } from "./combat.js";
export { setupMagic } from "./magic.js";
