import * as THREE from 'https://unpkg.com/three@0.160.0/build/three.module.js';

const $=id=>document.getElementById(id);
const ui={overlay:$('overlay'),start:$('start'),location:$('location'),objective:$('objective'),systems:$('systems'),alarm:$('alarmBanner'),message:$('message'),prompt:$('prompt'),vignette:$('vignette'),pad:$('movePad'),stick:$('moveStick'),run:$('runBtn'),lamp:$('lampBtn'),use:$('useBtn')};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050705);scene.fog=new THREE.FogExp2(0x171b18,.024);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.06,160);camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xaab8ad,0x11110f,.28));scene.add(camera);

const player={position:new THREE.Vector3(0,1.67,9),yaw:Math.PI,pitch:0,radius:.34,stamina:1,floor:6};
const world={started:false,dead:false,power:false,pressure:0,fuses:0,alarmPhase:'idle',alarmTimer:Infinity,eventTimer:0,exposure:0,survived:0,lamp:true,runHeld:false};
const sectors=new Map(),colliders=[],interactables=[],shelters=[],fixtures=[];
const tempV=new THREE.Vector3(),tempBox=new THREE.Box3(),raycaster=new THREE.Raycaster();
let aimed=null;

const material=(color,roughness=1,metalness=0,emissive=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness,emissive});
const M={wall:material(0x5b615b,.97),lower:material(0x31443a,.95),floor:material(0x343531,.98),ceiling:material(0x696e68,1),steel:material(0x4a514e,.55,.62),dark:material(0x111512,.9),rust:material(0x654638,.88,.22),pipe:material(0x45534c,.68,.5),red:material(0x7b2529,.72,.28),yellow:material(0xa7963f,.76,.18),glass:material(0xbcc8be,.28,.1,0x17231b),cloth:material(0x52514a,1),paper:material(0xbdb99f,1)};
function box(parent,x,y,z,w,h,d,mat=M.wall,solid=true){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);mesh.position.set(x,y,z);parent.add(mesh);if(solid)colliders.push({mesh,sector:parent.userData.sector,enabled:true});return mesh;}
function cyl(parent,x,y,z,r,h,mat=M.pipe,rz=Math.PI/2){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,10),mat);mesh.position.set(x,y,z);mesh.rotation.z=rz;parent.add(mesh);return mesh;}
function sign(parent,text,x,y,z,ry=0,scale=1){const c=document.createElement('canvas');c.width=512;c.height=128;const g=c.getContext('2d');g.fillStyle='#d6d1b5';g.fillRect(0,0,512,128);g.strokeStyle='#292d29';g.lineWidth=12;g.strokeRect(5,5,502,118);g.fillStyle='#252925';g.font='bold 52px monospace';g.textAlign='center';g.textBaseline='middle';g.fillText(text,256,64);const t=new THREE.CanvasTexture(c);const mesh=new THREE.Mesh(new THREE.PlaneGeometry(2.7*scale,.68*scale),new THREE.MeshBasicMaterial({map:t}));mesh.position.set(x,y,z);mesh.rotation.y=ry;parent.add(mesh);return mesh;}
function addInteract(mesh,type,data,text){mesh.userData={type,data,text};interactables.push(mesh);return mesh;}
function say(text,ms=2600){ui.message.textContent=text;ui.message.style.display='block';clearTimeout(say.t);say.t=setTimeout(()=>ui.message.style.display='none',ms);}
function seeded(n){const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x);}

function addFixture(group,x,z,index){box(group,x,3.0,z,2.4,.12,.42,M.dark,false);const panel=box(group,x,2.93,z,2.05,.03,.25,M.glass,false);const light=new THREE.PointLight(0xb9cabd,0,11,2);light.position.set(x,2.72,z);group.add(light);fixtures.push({group,light,panel,broken:seeded(index)>.82,phase:seeded(index+9)*7});}
function buildCorridor(group,z0,len,section){box(group,0,0,z0,6.8,.18,len,M.floor,true);box(group,0,3.18,z0,6.8,.18,len,M.ceiling,true);box(group,-3.32,1.55,z0,.22,3.2,len,M.wall,true);box(group,3.32,1.55,z0,.22,3.2,len,M.wall,true);box(group,-3.18,.75,z0,.08,1.4,len,M.lower,false);box(group,3.18,.75,z0,.08,1.4,len,M.lower,false);for(let z=z0-len/2+3;z<z0+len/2;z+=6)addFixture(group,0,z,Math.floor(z*11));for(let z=z0-len/2+1.4;z<z0+len/2;z+=7){cyl(group,-2.82,2.58,z,.075,7,M.pipe,0);box(group,-2.82,2.58,z,.25,.25,.08,M.dark,false);}sign(group,`F${player.floor} / ${section}`,2.95,2.15,z0-len/2+.6,-Math.PI/2,.62);}
function addDoor(group,side,z,id){const x=side*3.34;const pivot=new THREE.Group();pivot.position.set(x,0,z+(side<0?-.72:.72));group.add(pivot);const slab=box(pivot,0,1.18,side<0?.72:-.72,.14,2.35,1.42,M.steel,false);const collider={mesh:slab,sector:group.userData.sector,enabled:true};colliders.push(collider);const handle=cyl(pivot,side<0?.1:-.1,1.13,side<0?.28:-.28,.04,.34,M.yellow,Math.PI/2);const data={pivot,slab,collider,side,open:false,id};addInteract(slab,'door',data,'OPEN SHELTER DOOR');sign(group,String(id),x+(side<0?.12:-.12),2.18,z,side<0?Math.PI/2:-Math.PI/2,.42);return data;}
function addApartment(group,side,z,id,variant){const cx=side*6.15;box(group,cx,0,z,5.7,.18,5.2,M.floor,true);box(group,cx,3.18,z,5.7,.18,5.2,M.ceiling,true);box(group,side*8.92,1.55,z,.2,3.2,5.2,M.wall,true);box(group,cx,1.55,z-2.5,5.7,3.2,.2,M.wall,true);box(group,cx,1.55,z+2.5,5.7,3.2,.2,M.wall,true);box(group,side*3.42,1.55,z-1.78,.2,3.2,1.45,M.wall,true);box(group,side*3.42,1.55,z+1.78,.2,3.2,1.45,M.wall,true);const door=addDoor(group,side,z,id);box(group,cx+side*.65,.34,z+1.2,2.0,.5,1.0,variant%2?M.cloth:M.rust,true);box(group,cx-side*1.65,.42,z-1.45,.9,.82,.55,M.rust,true);box(group,cx-side*.65,.98,z-2.38,2.0,1.6,.08,M.dark,false);if(variant%3===0)box(group,cx-side*1.45,1.1,z+1.85,.75,2.0,.5,M.steel,true);if(variant%4===0){box(group,cx+side*1.55,.52,z-1.3,.8,1.0,.5,M.paper,true);cyl(group,cx+side*2.38,2.55,z,.055,4.35,M.pipe,0);}shelters.push({group,door,bounds:new THREE.Box3(new THREE.Vector3(Math.min(side*3.55,side*8.7),.1,z-2.35),new THREE.Vector3(Math.max(side*3.55,side*8.7),2.8,z+2.35))});}
function addBreakerPanel(group,z){const body=box(group,-3.0,1.35,z,.28,1.75,1.35,M.steel,true);sign(group,'AUX GRID',-3.16,2.45,z,Math.PI/2,.5);for(let i=0;i<3;i++){const sw=box(group,-3.18,1.7-i*.36,z-.28,.08,.2,.18,M.rust,false);addInteract(sw,'breaker',{index:i,on:false},`TOGGLE BREAKER ${i+1}`);}const fuseSlot=box(group,-3.18,.9,z+.34,.08,.38,.34,M.dark,false);addInteract(fuseSlot,'fuseSlot',{installed:false},'INSTALL CERAMIC FUSE');}
function addValve(group,z){cyl(group,3.0,1.35,z,.16,3.1,M.rust,0);const wheel=new THREE.Mesh(new THREE.TorusGeometry(.48,.055,8,20),M.red);wheel.position.set(2.65,1.35,z);wheel.rotation.y=Math.PI/2;group.add(wheel);for(let i=0;i<4;i++){const spoke=box(wheel,0,0,0,.05,.76,.05,M.red,false);spoke.rotation.z=i*Math.PI/2;}addInteract(wheel,'valve',{turns:0},'TURN RISER VALVE');sign(group,'SHELTER RISER',2.6,2.34,z,-Math.PI/2,.48);}
function addFusePickup(group,x,z){const fuse=box(group,x,.65,z,.22,.6,.22,M.paper,false);cyl(fuse,0,.3,0,.14,.11,M.yellow,0);addInteract(fuse,'fuse',{},'TAKE CERAMIC FUSE');}
function addUtilityBay(group,z,variant){box(group,-2.35,.46,z,1.2,.9,.8,variant%2?M.rust:M.steel,true);box(group,2.25,.55,z,1.35,1.1,.75,M.steel,true);for(let i=0;i<3;i++)cyl(group,-1+i,2.72,z,.065,1.4,M.pipe,Math.PI/2);if(variant%2===0)addFusePickup(group,2.15,z-.2);}
function addLaundry(group,z){for(const x of[-2.35,2.35]){const machine=box(group,x,.55,z,1.15,1.1,.75,M.steel,true);const glass=new THREE.Mesh(new THREE.CircleGeometry(.28,18),M.dark);glass.position.set(x,.62,z-.39);group.add(glass);}sign(group,'LAUNDRY',0,2.55,z-.42,0,.58);}
function addLift(group,z){box(group,0,1.55,z,6.6,3.1,.18,M.wall,true);box(group,-1.1,1.35,z-.15,2.1,2.65,.15,M.steel,false);box(group,1.1,1.35,z-.15,2.1,2.65,.15,M.steel,false);const btn=box(group,2.55,1.45,z-.2,.18,.18,.08,M.yellow,false);addInteract(btn,'lift',{},'CALL SERVICE LIFT');sign(group,'LIFT 4',0,2.85,z-.25,0,.65);}
function createSector(id){const group=new THREE.Group();group.userData.sector=id;const z0=id*36;const section=String.fromCharCode(65+((id%6+6)%6));buildCorridor(group,z0,36,section);for(let i=-2;i<=2;i++){if(i===0&&id%2===0)continue;const z=z0+i*6.2;addApartment(group,-1,z,600+id*10+i+3,Math.abs(id+i));addApartment(group,1,z,650+id*10+i+3,Math.abs(id-i));}
if(id===0){addBreakerPanel(group,z0-5);addFusePickup(group,2.2,z0+8);}
else if(id===1)addValve(group,z0+1);
else if(Math.abs(id)%4===2)addLaundry(group,z0);
else addUtilityBay(group,z0,Math.abs(id));
if(Math.abs(id)%5===3)addLift(group,z0+14.8);
for(let i=0;i<5;i++){const crate=box(group,i%2?2.45:-2.45,.24,z0-13+i*6,.62,.48,.62,i%3?M.rust:M.steel,true);crate.rotation.y=(i*.63)%1.2;}
scene.add(group);sectors.set(id,group);}
function unloadSector(id,group){scene.remove(group);sectors.delete(id);for(let i=colliders.length-1;i>=0;i--)if(colliders[i].sector===id)colliders.splice(i,1);for(let i=interactables.length-1;i>=0;i--)if(interactables[i].parent&&interactables[i].parent.parent===group||interactables[i].parent===group)interactables.splice(i,1);for(let i=shelters.length-1;i>=0;i--)if(shelters[i].group===group)shelters.splice(i,1);for(let i=fixtures.length-1;i>=0;i--)if(fixtures[i].group===group)fixtures.splice(i,1);}
function updateSectors(){const current=Math.floor((player.position.z+18)/36);for(let id=current-2;id<=current+2;id++)if(!sectors.has(id))createSector(id);for(const[id,group]of [...sectors])if(Math.abs(id-current)>3)unloadSector(id,group);ui.location.textContent=`F${String(player.floor).padStart(2,'0')} · SECTION ${String.fromCharCode(65+((current%6+6)%6))}`;}

const flashlight=new THREE.SpotLight(0xe8f3e7,4.1,20,.42,.55,1.45);flashlight.position.set(0,0,0);flashlight.target.position.set(0,0,-2);camera.add(flashlight,flashlight.target);
function blocked(pos){const sphere=new THREE.Sphere(new THREE.Vector3(pos.x,1,pos.z),player.radius);for(const c of colliders){if(!c.enabled||!c.mesh.parent)continue;tempBox.setFromObject(c.mesh);if(tempBox.intersectsSphere(sphere))return true;}return false;}
function movePlayer(dt,forward,side,running){const len=Math.hypot(forward,side);if(len>1){forward/=len;side/=len;}const speed=3.45*(running?1.65:1);const sin=Math.sin(player.yaw),cos=Math.cos(player.yaw);const dx=(sin*forward+cos*side)*speed*dt,dz=(-cos*forward+sin*side)*speed*dt;const nx=player.position.clone();nx.x+=dx;if(!blocked(nx))player.position.x=nx.x;const nz=player.position.clone();nz.z+=dz;if(!blocked(nz))player.position.z=nz.z;camera.position.copy(player.position);camera.rotation.set(player.pitch,player.yaw,0);}
function inSafeShelter(){for(const s of shelters){if(s.bounds.containsPoint(player.position)&&!s.door.open)return true;}return false;}
function updateAim(){raycaster.setFromCamera({x:0,y:0},camera);const hit=raycaster.intersectObjects(interactables,false).find(h=>h.distance<2.45&&h.object.visible);aimed=hit?.object||null;if(aimed){ui.prompt.textContent=`[ USE ] ${aimed.userData.text}`;ui.prompt.style.display='block';}else ui.prompt.style.display='none';}
function interact(obj){const {type,data}=obj.userData;
if(type==='door'){if(world.pressure<1){say('SEAL PRESSURE INSUFFICIENT');return;}data.open=!data.open;data.pivot.rotation.y=data.open*(data.side<0?-1.48:1.48);data.collider.enabled=!data.open;obj.userData.text=data.open?'CLOSE SHELTER DOOR':'OPEN SHELTER DOOR';}
if(type==='fuse'){world.fuses++;obj.visible=false;obj.userData.disabled=true;say('CERAMIC FUSE ACQUIRED');}
if(type==='fuseSlot'){if(data.installed)return;if(world.fuses<1){say('FUSE SLOT EMPTY');return;}world.fuses--;data.installed=true;obj.material=M.yellow;say('CONTROL FUSE INSTALLED');}
if(type==='breaker'){data.on=!data.on;obj.material=data.on?M.yellow:M.rust;const switches=interactables.filter(x=>x.userData.type==='breaker').map(x=>x.userData.data);const fuse=interactables.find(x=>x.userData.type==='fuseSlot')?.userData.data.installed;const correct=fuse&&switches[0]?.on&&!switches[1]?.on&&switches[2]?.on;if(correct&&!world.power){world.power=true;say('AUXILIARY GRID ONLINE');}}
if(type==='valve'){if(!world.power){say('PUMP BUS OFFLINE');return;}data.turns=Math.min(4,data.turns+1);obj.rotation.x+=Math.PI/2;world.pressure=data.turns/4;if(world.pressure>=1){say('SHELTER RISER PRESSURIZED');if(world.alarmPhase==='idle'){world.alarmPhase='quiet';world.alarmTimer=72;}}}
if(type==='lift'){if(!world.power){say('LIFT BUS OFFLINE');return;}say('SERVICE LIFT TRANSFER');setTimeout(()=>{player.floor=player.floor===6?7:6;player.position.z+=5;say(`ARRIVED FLOOR ${player.floor}`);},1100);}}
function use(){if(world.started&&!world.dead&&aimed)interact(aimed);}
function toggleLamp(){world.lamp=!world.lamp;flashlight.visible=world.lamp;}

let audioCtx=null,sirenGain=null,sirenOscA=null,sirenOscB=null;
function initAudio(){audioCtx=new (window.AudioContext||window.webkitAudioContext)();const master=audioCtx.createGain();master.gain.value=.22;master.connect(audioCtx.destination);sirenGain=audioCtx.createGain();sirenGain.gain.value=0;sirenGain.connect(master);sirenOscA=audioCtx.createOscillator();sirenOscB=audioCtx.createOscillator();sirenOscA.type='sawtooth';sirenOscB.type='square';sirenOscA.frequency.value=430;sirenOscB.frequency.value=218;sirenOscA.connect(sirenGain);sirenOscB.connect(sirenGain);sirenOscA.start();sirenOscB.start();}
function alarmSound(on){if(!audioCtx)return;const now=audioCtx.currentTime;sirenGain.gain.cancelScheduledValues(now);sirenGain.gain.linearRampToValueAtTime(on?.42:0,now+.12);}
function eventPhase(phase){world.alarmPhase=phase;if(phase==='warning'){world.alarmTimer=14;ui.alarm.textContent='CIVIL ALARM · SEEK SEALED SHELTER';ui.alarm.style.display='block';alarmSound(true);say('CIVIL ALARM — SHELTER IMMEDIATELY',5000);}if(phase==='active'){world.eventTimer=26;world.exposure=0;ui.alarm.textContent='SAMOSBOR IN PROGRESS';scene.background.setHex(0x25101f);scene.fog.color.setHex(0x5d2450);}if(phase==='quiet'){world.alarmTimer=58+Math.random()*45;world.exposure=0;ui.alarm.style.display='none';alarmSound(false);scene.background.setHex(0x050705);scene.fog.color.setHex(0x171b18);scene.fog.density=.024;renderer.toneMappingExposure=.9;}}
function updateEvent(dt){if(world.alarmPhase==='idle')return;if(world.alarmPhase==='quiet'){world.alarmTimer-=dt;if(world.alarmTimer<=0)eventPhase('warning');}else if(world.alarmPhase==='warning'){world.alarmTimer-=dt;if(world.alarmTimer<=0)eventPhase('active');}else if(world.alarmPhase==='active'){world.eventTimer-=dt;const safe=inSafeShelter();world.exposure=THREE.MathUtils.clamp(world.exposure+(safe?-dt*.28:dt*.22),0,1);scene.fog.density=.032+world.exposure*.12+Math.sin(performance.now()*.006)*.004;renderer.toneMappingExposure=.82-world.exposure*.46;ui.vignette.style.opacity=String(world.exposure);if(world.exposure>=1&&!world.dead){world.dead=true;alarmSound(false);say('BIOLOGICAL INTEGRITY LOST',99999);setTimeout(()=>location.reload(),3000);}if(world.eventTimer<=0){world.survived++;ui.vignette.style.opacity='0';eventPhase('quiet');say('EVENT TERMINATED — CORRIDORS REOPENED');}}}
function updateLights(now){for(const f of fixtures){let on=world.power&&!f.broken;if(world.alarmPhase==='warning')on=Math.sin(now*.02+f.phase)>-.25;if(world.alarmPhase==='active')on=Math.sin(now*.043+f.phase)>.72;f.light.color.setHex(world.alarmPhase==='warning'||world.alarmPhase==='active'?0xc52a31:0xb9cabd);f.light.intensity=on?1.05:.015;f.panel.material.emissive.setHex(on?0x17231b:0x030403);}}
function updateUI(){let objective='RESTORE AUXILIARY POWER';if(world.fuses===0&&!interactables.find(x=>x.userData.type==='fuseSlot')?.userData.data.installed)objective='FIND A CERAMIC FUSE';if(world.power&&world.pressure<1)objective='PRESSURIZE SHELTER RISER';if(world.pressure>=1)objective='EXPLORE · LISTEN FOR ALARM';ui.objective.textContent=objective;const phase=world.alarmPhase==='idle'?'DISARMED':world.alarmPhase==='quiet'?`QUIET ${Math.ceil(world.alarmTimer)}s`:world.alarmPhase==='warning'?`ALARM ${Math.ceil(world.alarmTimer)}s`:`ACTIVE ${Math.ceil(world.eventTimer)}s`;ui.systems.className='panel '+(world.alarmPhase==='active'?'danger':world.alarmPhase==='warning'?'warning':'');ui.systems.innerHTML=`POWER: ${world.power?'AUX':'OFF'}<br>RISER: ${Math.round(world.pressure*100)}%<br>EVENT: ${phase}<br>EXPOSURE: ${Math.round(world.exposure*100)}%<br>FUSES: ${world.fuses}`;}

let joyX=0,joyY=0,joyId=null,lookId=null,lastX=0,lastY=0;const keys={};
function moveStick(e){const r=ui.pad.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.34,len=Math.hypot(dx,dy)||1,m=Math.min(max,len);joyX=dx/len*m/max;joyY=dy/len*m/max;ui.stick.style.transform=`translate(${dx/len*m}px,${dy/len*m}px)`;}
function resetStick(){joyX=joyY=0;joyId=null;ui.stick.style.transform='translate(0,0)';}
addEventListener('pointerdown',e=>{if(!world.started||e.target.closest('button'))return;if(e.clientX<innerWidth*.42&&joyId===null){joyId=e.pointerId;moveStick(e);}else if(lookId===null){lookId=e.pointerId;lastX=e.clientX;lastY=e.clientY;}},{passive:false});
addEventListener('pointermove',e=>{if(e.pointerId===joyId)moveStick(e);if(e.pointerId===lookId){player.yaw-=(e.clientX-lastX)*.0032;player.pitch=THREE.MathUtils.clamp(player.pitch-(e.clientY-lastY)*.0027,-1.28,1.28);lastX=e.clientX;lastY=e.clientY;}},{passive:false});
addEventListener('pointerup',e=>{if(e.pointerId===joyId)resetStick();if(e.pointerId===lookId)lookId=null;});
ui.use.onpointerdown=e=>{e.preventDefault();use();};ui.lamp.onpointerdown=e=>{e.preventDefault();toggleLamp();};ui.run.onpointerdown=e=>{e.preventDefault();world.runHeld=true;};ui.run.onpointerup=ui.run.onpointercancel=()=>world.runHeld=false;
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')use();if(e.code==='KeyF')toggleLamp();});addEventListener('keyup',e=>keys[e.code]=false);
ui.start.onclick=()=>{world.started=true;ui.overlay.style.display='none';initAudio();say('AUXILIARY GRID REQUIRES A CERAMIC FUSE');};

updateSectors();
let last=performance.now();
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.04,(now-last)/1000);last=now;if(world.started&&!world.dead){const forward=-joyY+(keys.KeyW?1:0)-(keys.KeyS?1:0),side=joyX+(keys.KeyD?1:0)-(keys.KeyA?1:0);const running=(world.runHeld||keys.ShiftLeft)&&world.stamina>.04;world.stamina=THREE.MathUtils.clamp(world.stamina+(running?-dt*.24:dt*.15),0,1);movePlayer(dt,forward,side,running);updateSectors();updateAim();updateEvent(dt);updateLights(now);updateUI();}renderer.render(scene,camera);}frame(last);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});