import * as THREE from 'https://unpkg.com/three@0.160.0/build/three.module.js';

const $=id=>document.getElementById(id);
const ui={start:$('startScreen'),startBtn:$('startBtn'),zone:$('zone'),objective:$('objective'),status:$('topRight'),alarm:$('alarm'),prompt:$('prompt'),message:$('message'),damage:$('damage'),joy:$('joystick'),stick:$('stick'),lamp:$('lampBtn'),use:$('useBtn')};

const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc8dc);scene.fog=new THREE.Fog(0x9fc8dc,65,170);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.07,185);camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,.9));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xd9e9ee,0x242720,1.05));const sun=new THREE.DirectionalLight(0xffefc8,1.2);sun.position.set(-35,45,-20);scene.add(sun);

const M={wall:new THREE.MeshLambertMaterial({color:0x74786f}),wall2:new THREE.MeshLambertMaterial({color:0x62675f}),floor:new THREE.MeshLambertMaterial({color:0x42463f}),ceiling:new THREE.MeshLambertMaterial({color:0x555b54}),door:new THREE.MeshLambertMaterial({color:0x4e5c58}),wood:new THREE.MeshLambertMaterial({color:0x74583e}),fabric:new THREE.MeshLambertMaterial({color:0x6f6559}),metal:new THREE.MeshLambertMaterial({color:0x394442}),pipe:new THREE.MeshLambertMaterial({color:0x303a38}),lamp:new THREE.MeshBasicMaterial({color:0xf0f4de}),red:new THREE.MeshBasicMaterial({color:0x541217}),glass:new THREE.MeshBasicMaterial({color:0xaad9ec,transparent:true,opacity:.68}),city:new THREE.MeshLambertMaterial({color:0x878e89}),city2:new THREE.MeshLambertMaterial({color:0x707875})};
const GEO=new THREE.BoxGeometry(1,1,1),CELL=18,RADIUS=3;
const cells=new Map(),walls=[],doors=[],interactables=[],shelters=[],warnings=[];
function hash(a,b=0,c=0){const x=Math.sin(a*127.1+b*311.7+c*74.7)*43758.5453;return x-Math.floor(x);}
function id(x,z){return `${x},${z}`;}
function add(g,x,y,z,w,h,d,mat,solid=false){const m=new THREE.Mesh(GEO,mat);m.position.set(x,y,z);m.scale.set(w,h,d);m.updateMatrix();m.matrixAutoUpdate=false;g.add(m);if(solid){const c={minX:x-w/2,maxX:x+w/2,minZ:z-d/2,maxZ:z+d/2,enabled:true,owner:g};walls.push(c);g.userData.walls.push(c);}return m;}
function addDoor(g,x,z,axis,room){const p=new THREE.Group();p.position.set(x,0,z);g.add(p);const slab=new THREE.Mesh(GEO,M.door);slab.scale.set(axis==='x'?.15:1.45,2.45,axis==='z'?.15:1.45);slab.position.y=1.225;p.add(slab);const c={minX:x-(axis==='x'?.13:.8),maxX:x+(axis==='x'?.13:.8),minZ:z-(axis==='z'?.13:.8),maxZ:z+(axis==='z'?.13:.8),enabled:true,owner:g};walls.push(c);g.userData.walls.push(c);const d={pivot:p,slab,col:c,axis,open:false,room};slab.userData.door=d;doors.push(d);interactables.push(slab);g.userData.doors.push(d);return d;}
function room(g,cx,cz,corner,seed){const sx=corner.includes('E')?1:-1,sz=corner.includes('S')?1:-1,x=cx+sx*5.6,z=cz+sz*5.6,w=5.2,d=5.2;add(g,x,-.09,z,w,.18,d,M.floor);add(g,x,3.15,z,w,.18,d,M.ceiling);add(g,x+sx*w/2,1.53,z,.2,3.25,d,M.wall,true);add(g,x,1.53,z+sz*d/2,w,3.25,.2,M.wall,true);add(g,x-sx*w/2,1.53,z+sz*1.78,.2,3.25,1.62,M.wall,true);add(g,x-sx*w/2,1.53,z-sz*1.78,.2,3.25,1.62,M.wall,true);add(g,x-sx*w/2,2.82,z,.22,.62,2.05,M.wall2,true);add(g,x,.3,z+sz*1.45,2.2,.6,1.05,M.fabric,true);add(g,x+sx*1.4,.45,z-sz*1.4,1,.9,.7,M.wood,true);const r={minX:x-w/2+.15,maxX:x+w/2-.15,minZ:z-d/2+.15,maxZ:z+d/2-.15,door:null};r.door=addDoor(g,x-sx*w/2,z,'x',r);shelters.push(r);g.userData.shelters.push(r);}
function edgeOpen(x,z,dir){if(x===0&&z===0)return true;if(dir==='E')return edgeOpen(x+1,z,'W');if(dir==='S')return edgeOpen(x,z+1,'N');const forced=dir==='N'?x%3===0:z%3===0;return forced||hash(x,z,dir==='N'?1:2)>.5;}
function edge(g,cx,cz,dir,open){const H=3.25,L=CELL/2,gap=4.6;if(dir==='N'||dir==='S'){const z=cz+(dir==='S'?L:-L);if(open){add(g,cx-(CELL+gap)/4,1.53,z,(CELL-gap)/2,H,.2,M.wall,true);add(g,cx+(CELL+gap)/4,1.53,z,(CELL-gap)/2,H,.2,M.wall,true);}else add(g,cx,1.53,z,CELL,H,.2,M.wall,true);}else{const x=cx+(dir==='E'?L:-L);if(open){add(g,x,1.53,cz-(CELL+gap)/4,.2,H,(CELL-gap)/2,M.wall,true);add(g,x,1.53,cz+(CELL+gap)/4,.2,H,(CELL-gap)/2,M.wall,true);}else add(g,x,1.53,cz,.2,H,CELL,M.wall,true);}}
function decorate(g,cx,cz,type){if(type==='SERVICE'){add(g,cx-6.7,2.55,cz,.18,.18,14,M.pipe);add(g,cx+6.7,.6,cz,.55,1,12,M.metal);for(let q=-5;q<=5;q+=5)add(g,cx+q,.5,cz+5,1.1,1,1.1,M.metal,true);}else if(type==='LOBBY'){for(let q=-5;q<=5;q+=5)add(g,cx+q,.45,cz+4,1.1,.9,1.1,M.metal,true);add(g,cx,2.55,cz-6,12,.22,.22,M.pipe);}else{add(g,cx-7.1,2.65,cz,.14,.14,12,M.pipe);add(g,cx+7.1,2.45,cz,.14,.14,12,M.pipe);}}
function buildCell(gx,gz){const g=new THREE.Group();g.userData={gx,gz,walls:[],doors:[],shelters:[],warnings:[],type:'RESIDENTIAL'};const cx=gx*CELL,cz=gz*CELL,n=edgeOpen(gx,gz,'N'),s=edgeOpen(gx,gz,'S'),e=edgeOpen(gx,gz,'E'),w=edgeOpen(gx,gz,'W');add(g,cx,-.1,cz,CELL,.2,CELL,M.floor);add(g,cx,3.18,cz,CELL,.2,CELL,M.ceiling);edge(g,cx,cz,'N',n);edge(g,cx,cz,'S',s);edge(g,cx,cz,'E',e);edge(g,cx,cz,'W',w);add(g,cx,3.01,cz,1.7,.07,.3,M.lamp);add(g,cx,3.01,cz-6,1.2,.07,.25,M.lamp);add(g,cx,3.01,cz+6,1.2,.07,.25,M.lamp);const warn=add(g,cx,2.73,cz+1,.46,.2,.14,M.red);warnings.push(warn);g.userData.warnings.push(warn);const openings=[n,s,e,w].filter(Boolean).length,r=hash(gx,gz,9);let type='RESIDENTIAL';if(gx===0&&gz===0)type='START HUB';else if(r<.2)type='SERVICE';else if(r<.42||openings>=3)type='LOBBY';g.userData.type=type;decorate(g,cx,cz,type);const corners=[];if(!n&&!w)corners.push('NW');if(!n&&!e)corners.push('NE');if(!s&&!w)corners.push('SW');if(!s&&!e)corners.push('SE');if(corners.length&&!(gx===0&&gz===0))room(g,cx,cz,corners[Math.floor(hash(gx,gz,12)*corners.length)],gx*97+gz*53);for(let i=0;i<4;i++){const rr=hash(gx*13+i,gz*17-i),side=i%2?1:-1,x=cx+side*(26+i*8),z=cz+(rr-.5)*34,h=18+Math.floor(rr*6)*5;add(g,x,h/2-1,z,9+(i%3)*3,h,10+(i%2)*4,i%2?M.city:M.city2);}scene.add(g);cells.set(id(gx,gz),g);}
function removeCell(k){const g=cells.get(k);if(!g)return;for(const d of g.userData.doors){doors.splice(doors.indexOf(d),1);interactables.splice(interactables.indexOf(d.slab),1);}for(const r of g.userData.shelters)shelters.splice(shelters.indexOf(r),1);for(const c of g.userData.walls)walls.splice(walls.indexOf(c),1);for(const w of g.userData.warnings)warnings.splice(warnings.indexOf(w),1);scene.remove(g);cells.delete(k);}
function stream(){const gx=Math.floor((player.pos.x+CELL/2)/CELL),gz=Math.floor((player.pos.z+CELL/2)/CELL);for(let x=gx-RADIUS;x<=gx+RADIUS;x++)for(let z=gz-RADIUS;z<=gz+RADIUS;z++)if(!cells.has(id(x,z)))buildCell(x,z);for(const [k,g] of [...cells])if(Math.abs(g.userData.gx-gx)>RADIUS+1||Math.abs(g.userData.gz-gz)>RADIUS+1)removeCell(k);}

const player={pos:new THREE.Vector3(0,1.67,0),yaw:Math.PI,pitch:0,radius:.34,exposure:0};const flashlight=new THREE.SpotLight(0xf6fff2,8,28,.5,.55,1.1);flashlight.position.set(0,.05,.05);flashlight.target.position.set(0,-.05,-3);camera.add(flashlight,flashlight.target);scene.add(camera);const ray=new THREE.Raycaster();let aimed=null,started=false,lampOn=true;
function overlap(c,p){return p.x+player.radius>c.minX&&p.x-player.radius<c.maxX&&p.z+player.radius>c.minZ&&p.z-player.radius<c.maxZ;}
function blocked(next,current){for(const c of walls){if(!c.enabled)continue;if(overlap(c,current))continue;if(overlap(c,next))return true;}return false;}
function updateAim(){ray.setFromCamera({x:0,y:0},camera);const hit=ray.intersectObjects(interactables,false).find(h=>h.distance<3.5);aimed=hit?.object||null;ui.prompt.style.display=aimed?'block':'none';if(aimed)ui.prompt.textContent=`[ USE ] ${aimed.userData.door.open?'CLOSE':'OPEN'} DOOR`;}
function use(){if(!aimed)return;const d=aimed.userData.door;d.open=!d.open;d.pivot.rotation.y=d.open*1.5;d.col.enabled=!d.open;}
function toggleLamp(){lampOn=!lampOn;flashlight.visible=lampOn;ui.lamp.textContent=lampOn?'LAMP':'LAMP OFF';}
function safe(){return shelters.some(r=>player.pos.x>r.minX&&player.pos.x<r.maxX&&player.pos.z>r.minZ&&player.pos.z<r.maxZ&&!r.door.open);}
let ac=null,osc=null,gain=null;function alarmOn(){if(!ac)ac=new(window.AudioContext||window.webkitAudioContext)();if(osc)return;osc=ac.createOscillator();gain=ac.createGain();osc.type='square';osc.frequency.value=420;gain.gain.value=.032;osc.connect(gain).connect(ac.destination);osc.start();}function alarmOff(){if(osc){osc.stop();osc=null;gain=null;}}
const event={state:'normal',timer:300+hash(Date.now())*240,cycle:0};function setEvent(state,time){event.state=state;event.timer=time;if(state==='warning'||state==='active')alarmOn();else alarmOff();}
function relocate(){player.pos.set(0,1.67,0);player.exposure=0;ui.message.textContent='EXPOSURE DETECTED — EMERGENCY RELOCATION';ui.message.style.display='block';setTimeout(()=>ui.message.style.display='none',2600);}
function updateEvent(dt){event.timer-=dt;if(event.state==='normal'&&event.timer<=0)setEvent('warning',22);else if(event.state==='warning'&&event.timer<=0)setEvent('active',20);else if(event.state==='active'&&event.timer<=0){event.cycle++;setEvent('clear',8);}else if(event.state==='clear'&&event.timer<=0)setEvent('normal',180+hash(event.cycle,43)*240);const flash=(event.state==='warning'||event.state==='active')&&Math.floor(performance.now()/260)%2===0;for(const w of warnings)w.material=flash?M.lamp:M.red;if(event.state==='warning'){ui.alarm.style.display='block';ui.alarm.textContent=`САМОСБОР WARNING — SEEK SHELTER ${Math.ceil(event.timer)}s`;ui.objective.textContent='ENTER A ROOM AND CLOSE THE DOOR';}else if(event.state==='active'){const sealed=safe();ui.alarm.style.display='block';ui.alarm.textContent=sealed?'САМОСБОР ACTIVE — SHELTER SEALED':'САМОСБОР ACTIVE — EXPOSED';ui.objective.textContent=sealed?'WAIT FOR THE ALL-CLEAR':'GET BEHIND A CLOSED DOOR';if(!sealed){player.exposure+=dt;ui.damage.style.opacity=Math.min(1,player.exposure/1.5);if(player.exposure>3)relocate();}else{player.exposure=Math.max(0,player.exposure-dt*2);ui.damage.style.opacity=0;}}else if(event.state==='clear'){ui.alarm.style.display='block';ui.alarm.textContent='ALL CLEAR — CORRIDORS SAFE';ui.objective.textContent='CONTINUE THROUGH THE COMBINE';ui.damage.style.opacity=0;}else{ui.alarm.style.display='none';ui.objective.textContent='EXPLORE THE ENDLESS RESIDENTIAL COMBINE';ui.damage.style.opacity=0;}if(osc){osc.frequency.value=flash?510:390;gain.gain.value=event.state==='active'?.052:.032;}}
function hud(){const gx=Math.floor((player.pos.x+CELL/2)/CELL),gz=Math.floor((player.pos.z+CELL/2)/CELL),g=cells.get(id(gx,gz));ui.zone.textContent=`${g?.userData.type||'COMBINE'} — GRID ${gx},${gz}`;ui.status.innerHTML=`LAMP: ${lampOn?'ON':'OFF'}<br>EVENT: ${event.state.toUpperCase()}<br>WORLD: 2D STREAMING`;}

let joyX=0,joyY=0,joyId=null,lookId=null,lx=0,ly=0;const keys={};function moveStick(t){const r=ui.joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=t.clientX-cx,dy=t.clientY-cy,len=Math.hypot(dx,dy),max=r.width*.34,m=Math.min(max,len),nx=len?dx/len:0,ny=len?dy/len:0;joyX=nx*m/max;joyY=ny*m/max;ui.stick.style.transform=`translate(${nx*m}px,${ny*m}px)`;}function resetStick(){joyX=joyY=0;joyId=null;ui.stick.style.transform='translate(0,0)';}
addEventListener('touchstart',e=>{if(!started)return;e.preventDefault();for(const t of e.changedTouches){const el=document.elementFromPoint(t.clientX,t.clientY);if(el?.closest('#buttons'))continue;if(t.clientX<innerWidth*.44&&joyId===null){joyId=t.identifier;moveStick(t);}else if(lookId===null){lookId=t.identifier;lx=t.clientX;ly=t.clientY;}}},{passive:false});addEventListener('touchmove',e=>{if(!started)return;e.preventDefault();for(const t of e.changedTouches){if(t.identifier===joyId)moveStick(t);if(t.identifier===lookId){const dx=t.clientX-lx,dy=t.clientY-ly;lx=t.clientX;ly=t.clientY;player.yaw-=dx*.0037;player.pitch=THREE.MathUtils.clamp(player.pitch+dy*.003,-1.05,.75);}}},{passive:false});addEventListener('touchend',e=>{for(const t of e.changedTouches){if(t.identifier===joyId)resetStick();if(t.identifier===lookId)lookId=null;}});addEventListener('touchcancel',()=>{resetStick();lookId=null;});
function bind(el,fn){el.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();fn();});}bind(ui.use,use);bind(ui.lamp,toggleLamp);addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')use();if(e.code==='KeyF')toggleLamp();});addEventListener('keyup',e=>keys[e.code]=false);ui.startBtn.onclick=()=>{started=true;ui.start.style.display='none';stream();if(ac)ac.resume();};
stream();let last=performance.now(),hudTick=0;function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;if(started){let f=-joyY+(keys.KeyW?1:0)-(keys.KeyS?1:0),s=joyX+(keys.KeyD?1:0)-(keys.KeyA?1:0),n=Math.hypot(f,s);if(n>1){f/=n;s/=n;}const speed=5.8,sn=Math.sin(player.yaw),cs=Math.cos(player.yaw),dx=(s*cs-f*sn)*speed*dt,dz=(-s*sn-f*cs)*speed*dt;const current=player.pos.clone(),px=current.clone();px.x+=dx;if(!blocked(px,current))player.pos.x=px.x;const current2=player.pos.clone(),pz=current2.clone();pz.z+=dz;if(!blocked(pz,current2))player.pos.z=pz.z;camera.position.copy(player.pos);camera.rotation.set(player.pitch,player.yaw,0);stream();updateAim();updateEvent(dt);if(now-hudTick>250){hud();hudTick=now;}}renderer.render(scene,camera);}frame(last);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});