import * as THREE from 'https://unpkg.com/three@0.160.0/build/three.module.js';

const $=id=>document.getElementById(id);
const ui={start:$('startScreen'),startBtn:$('startBtn'),zone:$('zone'),objective:$('objective'),status:$('topRight'),alarm:$('alarm'),prompt:$('prompt'),message:$('message'),damage:$('damage'),joy:$('joystick'),stick:$('stick'),lamp:$('lampBtn'),use:$('useBtn')};

const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc8dc);scene.fog=new THREE.Fog(0x9fc8dc,65,170);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.07,185);camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance',precision:'mediump'});renderer.setPixelRatio(Math.min(devicePixelRatio,.9));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xd9e9ee,0x242720,1.05));const sun=new THREE.DirectionalLight(0xffefc8,1.2);sun.position.set(-35,45,-20);scene.add(sun);

const M={wall:new THREE.MeshLambertMaterial({color:0x74786f}),wall2:new THREE.MeshLambertMaterial({color:0x62675f}),floor:new THREE.MeshLambertMaterial({color:0x42463f}),ceiling:new THREE.MeshLambertMaterial({color:0x555b54}),door:new THREE.MeshLambertMaterial({color:0x4e5c58}),wood:new THREE.MeshLambertMaterial({color:0x74583e}),fabric:new THREE.MeshLambertMaterial({color:0x6f6559}),metal:new THREE.MeshLambertMaterial({color:0x394442}),pipe:new THREE.MeshLambertMaterial({color:0x303a38}),lamp:new THREE.MeshBasicMaterial({color:0xf0f4de}),red:new THREE.MeshBasicMaterial({color:0x541217}),glass:new THREE.MeshBasicMaterial({color:0xaad9ec,transparent:true,opacity:.68}),city:new THREE.MeshLambertMaterial({color:0x878e89}),city2:new THREE.MeshLambertMaterial({color:0x707875})};
const G=new THREE.BoxGeometry(1,1,1),CELL=18,RADIUS=3;
const cells=new Map(),colliders=[],doors=[],interactables=[],shelters=[],warnings=[],ramps=[],upperZones=[];
function hash(a,b=0,c=0){const x=Math.sin(a*127.1+b*311.7+c*74.7)*43758.5453;return x-Math.floor(x);}
function key(x,z){return `${x},${z}`;}
function box(g,x,y,z,w,h,d,mat,solid=true){const m=new THREE.Mesh(G,mat);m.position.set(x,y,z);m.scale.set(w,h,d);m.updateMatrix();m.matrixAutoUpdate=false;g.add(m);if(solid){const c={minX:x-w/2,maxX:x+w/2,minY:y-h/2,maxY:y+h/2,minZ:z-d/2,maxZ:z+d/2,enabled:true,owner:g};colliders.push(c);g.userData.colliders.push(c);}return m;}
function makeDoor(g,x,y,z,axis,room){const p=new THREE.Group();p.position.set(x,y,z);g.add(p);const slab=new THREE.Mesh(G,M.door);slab.scale.set(axis==='x'?.15:1.45,2.45,axis==='z'?.15:1.45);slab.position.y=1.225;p.add(slab);const c={minX:x-(axis==='x'?.13:.8),maxX:x+(axis==='x'?.13:.8),minY:y,maxY:y+2.5,minZ:z-(axis==='z'?.13:.8),maxZ:z+(axis==='z'?.13:.8),enabled:true,owner:g};colliders.push(c);g.userData.colliders.push(c);const d={pivot:p,slab,col:c,axis,open:false,room,owner:g};slab.userData.door=d;doors.push(d);interactables.push(slab);g.userData.doors.push(d);return d;}
function safeRoom(g,cx,cz,corner,seed,y=0){const sx=corner.includes('E')?1:-1,sz=corner.includes('S')?1:-1,x=cx+sx*5.5,z=cz+sz*5.5,w=5.4,d=5.4;box(g,x,y-.09,z,w,.18,d,M.floor);box(g,x,y+3.15,z,w,.18,d,M.ceiling);box(g,x+sx*w/2,y+1.53,z,.2,3.25,d,M.wall);box(g,x,y+1.53,z+sz*d/2,w,3.25,.2,M.wall);box(g,x-sx*w/2,y+1.53,z+sz*1.85,.2,3.25,1.7,M.wall);box(g,x-sx*w/2,y+1.53,z-sz*1.85,.2,3.25,1.7,M.wall);box(g,x-sx*w/2,y+2.82,z,.22,.62,2.1,M.wall2);box(g,x,y+.3,z+sz*1.5,2.2,.6,1.05,M.fabric);box(g,x+sx*1.4,y+.45,z-sz*1.45,1,.9,.7,M.wood);const room={minX:x-w/2+.12,maxX:x+w/2-.12,minZ:z-d/2+.12,maxZ:z+d/2-.12,minY:y,maxY:y+3,door:null};room.door=makeDoor(g,x-sx*w/2,y,z,'x',room);shelters.push(room);g.userData.shelters.push(room);}
function edgeOpen(x,z,dir){if(dir==='E')return edgeOpen(x+1,z,'W');if(dir==='S')return edgeOpen(x,z+1,'N');let a=x,b=z,c=dir==='N'?1:2;const random=hash(a,b,c)>.48;const grid=dir==='N'?(x%3===0):(z%3===0);return random||grid||((x===0||z===0)&&hash(a,b,c)>.25);}
function wallEdge(g,cx,cz,dir,open,y=0){const gap=4.4,L=CELL/2;if(dir==='N'||dir==='S'){const z=cz+(dir==='S'?L:-L);if(open){box(g,cx-(CELL+gap)/4,y+1.53,z,(CELL-gap)/2,3.25,.2,M.wall);box(g,cx+(CELL+gap)/4,y+1.53,z,(CELL-gap)/2,3.25,.2,M.wall);}else box(g,cx,y+1.53,z,CELL,3.25,.2,M.wall);}else{const x=cx+(dir==='E'?L:-L);if(open){box(g,x,y+1.53,cz-(CELL+gap)/4,.2,3.25,(CELL-gap)/2,M.wall);box(g,x,y+1.53,cz+(CELL+gap)/4,.2,3.25,(CELL-gap)/2,M.wall);}else box(g,x,y+1.53,cz,.2,3.25,CELL,M.wall);}}
function addLights(g,cx,cz,y=0){box(g,cx,y+3.01,cz,1.7,.07,.3,M.lamp,false);box(g,cx,y+3.01,cz-6,1.2,.07,.25,M.lamp,false);box(g,cx,y+3.01,cz+6,1.2,.07,.25,M.lamp,false);const w=box(g,cx,y+2.73,cz+1,.46,.2,.14,M.red,false);warnings.push(w);g.userData.warnings.push(w);}
function addCity(g,cx,cz,gx,gz){for(let i=0;i<5;i++){const r=hash(gx*13+i,gz*17-i),side=i%2?1:-1,x=cx+side*(28+i*8),z=cz+(r-.5)*40,h=18+Math.floor(r*6)*5;box(g,x,h/2-1,z,9+(i%3)*3,h,10+(i%2)*4,i%2?M.city:M.city2,false);}}
function serviceDecor(g,cx,cz){box(g,cx-6.7,2.55,cz,.18,.18,14,M.pipe,false);box(g,cx+6.7,.6,cz,.55,1,12,M.metal,false);for(let i=-1;i<=1;i++)box(g,cx+i*4,.5,cz+5,1.1,1,1.1,M.metal);}
function lobbyDecor(g,cx,cz){for(let x=-5;x<=5;x+=5)box(g,cx+x,.45,cz,1.1,.9,1.1,M.metal);box(g,cx,2.55,cz-6,12,.22,.22,M.pipe,false);}
function stairDecor(g,cx,cz,seed){const side=hash(seed,8)>.5?1:-1;for(let i=0;i<13;i++){const t=i/12,x=cx+side*(-5.5+t*10.5),y=.13+t*3.8;box(g,x,y,cz,1,.24,3,M.metal);}const r={owner:g,minX:cx-6,maxX:cx+6,minZ:cz-1.7,maxZ:cz+1.7,side,y:3.8};ramps.push(r);g.userData.ramps.push(r);box(g,cx+side*7.2,3.7,cz,4,.2,8,M.floor);box(g,cx+side*7.2,6.85,cz,4,.18,8,M.ceiling);upperZones.push({owner:g,minX:cx+side*5,maxX:cx+side*9,minZ:cz-4,maxZ:cz+4,y:3.8});g.userData.upperZones.push(upperZones[upperZones.length-1]);box(g,cx+side*8.9,5.35,cz,.2,3.1,8,M.wall);}
function buildCell(gx,gz){const g=new THREE.Group();g.userData={gx,gz,colliders:[],doors:[],shelters:[],warnings:[],ramps:[],upperZones:[]};const cx=gx*CELL,cz=gz*CELL,n=edgeOpen(gx,gz,'N'),s=edgeOpen(gx,gz,'S'),e=edgeOpen(gx,gz,'E'),w=edgeOpen(gx,gz,'W');box(g,cx,-.1,cz,CELL,.2,CELL,M.floor);box(g,cx,3.18,cz,CELL,.2,CELL,M.ceiling);wallEdge(g,cx,cz,'N',n);wallEdge(g,cx,cz,'S',s);wallEdge(g,cx,cz,'E',e);wallEdge(g,cx,cz,'W',w);addLights(g,cx,cz);const openings=[n,s,e,w].filter(Boolean).length,r=hash(gx,gz,9);let type='RESIDENTIAL JUNCTION';if(r<.18){type='SERVICE';serviceDecor(g,cx,cz);}else if(r<.34||openings>=3){type='LOBBY';lobbyDecor(g,cx,cz);}else if(r<.46){type='STAIRWELL';stairDecor(g,cx,cz,gx*31+gz*17);}else{box(g,cx-7.1,2.65,cz,.14,.14,12,M.pipe,false);box(g,cx+7.1,2.45,cz,.14,.14,12,M.pipe,false);}const corners=[];if(!n&&!w)corners.push('NW');if(!n&&!e)corners.push('NE');if(!s&&!w)corners.push('SW');if(!s&&!e)corners.push('SE');if(corners.length){safeRoom(g,cx,cz,corners[Math.floor(hash(gx,gz,12)*corners.length)],gx*97+gz*53);}else if(openings<=2){safeRoom(g,cx,cz,hash(gx,gz,13)>.5?'NE':'SW',gx*71+gz*29);}g.userData.type=type;addCity(g,cx,cz,gx,gz);scene.add(g);cells.set(key(gx,gz),g);}
function removeCell(k){const g=cells.get(k);if(!g)return;for(const d of g.userData.doors){doors.splice(doors.indexOf(d),1);interactables.splice(interactables.indexOf(d.slab),1);}for(const s of g.userData.shelters)shelters.splice(shelters.indexOf(s),1);for(const c of g.userData.colliders)colliders.splice(colliders.indexOf(c),1);for(const w of g.userData.warnings)warnings.splice(warnings.indexOf(w),1);for(const r of g.userData.ramps)ramps.splice(ramps.indexOf(r),1);for(const u of g.userData.upperZones)upperZones.splice(upperZones.indexOf(u),1);scene.remove(g);cells.delete(k);}
function stream(){const gx=Math.floor((player.pos.x+CELL/2)/CELL),gz=Math.floor((player.pos.z+CELL/2)/CELL);for(let x=gx-RADIUS;x<=gx+RADIUS;x++)for(let z=gz-RADIUS;z<=gz+RADIUS;z++)if(!cells.has(key(x,z)))buildCell(x,z);for(const [k,g] of cells)if(Math.abs(g.userData.gx-gx)>RADIUS+1||Math.abs(g.userData.gz-gz)>RADIUS+1)removeCell(k);}
function floorAt(x,z,current){for(const r of ramps){if(x>=r.minX&&x<=r.maxX&&z>=r.minZ&&z<=r.maxZ){const t=r.side>0?(x-r.minX)/(r.maxX-r.minX):(r.maxX-x)/(r.maxX-r.minX);return THREE.MathUtils.clamp(t,0,1)*r.y;}}for(const u of upperZones)if(x>=u.minX&&x<=u.maxX&&z>=u.minZ&&z<=u.maxZ)return u.y;return current>2?3.8:0;}

const player={pos:new THREE.Vector3(0,1.67,0),yaw:Math.PI,pitch:0,radius:.34,exposure:0};const flashlight=new THREE.SpotLight(0xf6fff2,8,28,.5,.55,1.1);flashlight.position.set(0,.05,.05);flashlight.target.position.set(0,-.05,-3);camera.add(flashlight,flashlight.target);scene.add(camera);const ray=new THREE.Raycaster();let aimed=null,started=false,lampOn=true;
function blocked(p){const foot=p.y-1.02;for(const c of colliders){if(!c.enabled)continue;if(p.x+player.radius<c.minX||p.x-player.radius>c.maxX||foot+1.05<c.minY||foot>c.maxY||p.z+player.radius<c.minZ||p.z-player.radius>c.maxZ)continue;return true;}return false;}
function updateAim(){ray.setFromCamera({x:0,y:0},camera);const hit=ray.intersectObjects(interactables,false).find(h=>h.distance<3.5);aimed=hit?.object||null;ui.prompt.style.display=aimed?'block':'none';if(aimed)ui.prompt.textContent=`[ USE ] ${aimed.userData.door.open?'CLOSE':'OPEN'} DOOR`;}
function use(){if(!aimed)return;const d=aimed.userData.door;d.open=!d.open;d.pivot.rotation.y=d.open*1.5;d.col.enabled=!d.open;}
function toggleLamp(){lampOn=!lampOn;flashlight.visible=lampOn;ui.lamp.textContent=lampOn?'LAMP':'LAMP OFF';}
function safe(){return shelters.some(s=>player.pos.x>s.minX&&player.pos.x<s.maxX&&player.pos.z>s.minZ&&player.pos.z<s.maxZ&&player.pos.y-1.67>=s.minY-.2&&player.pos.y-1.67<=s.maxY&&!s.door.open);}
let ac=null,osc=null,gain=null;function alarmOn(){if(!ac)ac=new(window.AudioContext||window.webkitAudioContext)();if(osc)return;osc=ac.createOscillator();gain=ac.createGain();osc.type='square';osc.frequency.value=420;gain.gain.value=.032;osc.connect(gain).connect(ac.destination);osc.start();}function alarmOff(){if(osc){osc.stop();osc=null;gain=null;}}
const event={state:'normal',timer:300+hash(Date.now())*240,cycle:0};function setEvent(state,time){event.state=state;event.timer=time;if(state==='warning'||state==='active')alarmOn();else alarmOff();}
function relocate(){player.pos.set(0,1.67,0);player.exposure=0;ui.message.textContent='EXPOSURE DETECTED — EMERGENCY RELOCATION';ui.message.style.display='block';setTimeout(()=>ui.message.style.display='none',2600);}
function updateEvent(dt){event.timer-=dt;if(event.state==='normal'&&event.timer<=0)setEvent('warning',22);else if(event.state==='warning'&&event.timer<=0)setEvent('active',20);else if(event.state==='active'&&event.timer<=0){event.cycle++;setEvent('clear',8);}else if(event.state==='clear'&&event.timer<=0)setEvent('normal',180+hash(event.cycle,43)*240);const flash=(event.state==='warning'||event.state==='active')&&Math.floor(performance.now()/260)%2===0;for(const w of warnings)w.material=flash?M.lamp:M.red;if(event.state==='warning'){ui.alarm.style.display='block';ui.alarm.textContent=`САМОСБОР WARNING — SEEK SHELTER ${Math.ceil(event.timer)}s`;ui.objective.textContent='ENTER A ROOM AND CLOSE THE DOOR';}else if(event.state==='active'){const sealed=safe();ui.alarm.style.display='block';ui.alarm.textContent=sealed?'САМОСБОР ACTIVE — SHELTER SEALED':'САМОСБОР ACTIVE — EXPOSED';ui.objective.textContent=sealed?'WAIT FOR THE ALL-CLEAR':'GET BEHIND A CLOSED DOOR';if(!sealed){player.exposure+=dt;ui.damage.style.opacity=Math.min(1,player.exposure/1.5);if(player.exposure>3)relocate();}else{player.exposure=Math.max(0,player.exposure-dt*2);ui.damage.style.opacity=0;}}else if(event.state==='clear'){ui.alarm.style.display='block';ui.alarm.textContent='ALL CLEAR — CORRIDORS SAFE';ui.objective.textContent='CONTINUE THROUGH THE COMBINE';ui.damage.style.opacity=0;}else{ui.alarm.style.display='none';ui.objective.textContent='EXPLORE THE ENDLESS RESIDENTIAL COMBINE';ui.damage.style.opacity=0;}if(osc){osc.frequency.value=flash?510:390;gain.gain.value=event.state==='active'?.052:.032;}}
function hud(){const gx=Math.floor((player.pos.x+CELL/2)/CELL),gz=Math.floor((player.pos.z+CELL/2)/CELL),g=cells.get(key(gx,gz)),level=player.pos.y>3?'UPPER LEVEL':'LOWER LEVEL';ui.zone.textContent=`${g?.userData.type||'COMBINE'} — ${level} — GRID ${gx},${gz}`;ui.status.innerHTML=`LAMP: ${lampOn?'ON':'OFF'}<br>EVENT: ${event.state.toUpperCase()}<br>WORLD: 2D STREAMING`;}

let joyX=0,joyY=0,joyId=null,lookId=null,lx=0,ly=0;const keys={};function moveStick(t){const r=ui.joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=t.clientX-cx,dy=t.clientY-cy,len=Math.hypot(dx,dy),max=r.width*.34,m=Math.min(max,len),nx=len?dx/len:0,ny=len?dy/len:0;joyX=nx*m/max;joyY=ny*m/max;ui.stick.style.transform=`translate(${nx*m}px,${ny*m}px)`;}function resetStick(){joyX=joyY=0;joyId=null;ui.stick.style.transform='translate(0,0)';}
addEventListener('touchstart',e=>{if(!started)return;e.preventDefault();for(const t of e.changedTouches){const el=document.elementFromPoint(t.clientX,t.clientY);if(el?.closest('#buttons'))continue;if(t.clientX<innerWidth*.44&&joyId===null){joyId=t.identifier;moveStick(t);}else if(lookId===null){lookId=t.identifier;lx=t.clientX;ly=t.clientY;}}},{passive:false});addEventListener('touchmove',e=>{if(!started)return;e.preventDefault();for(const t of e.changedTouches){if(t.identifier===joyId)moveStick(t);if(t.identifier===lookId){const dx=t.clientX-lx,dy=t.clientY-ly;lx=t.clientX;ly=t.clientY;player.yaw-=dx*.0037;player.pitch=THREE.MathUtils.clamp(player.pitch+dy*.003,-1.05,.75);}}},{passive:false});addEventListener('touchend',e=>{for(const t of e.changedTouches){if(t.identifier===joyId)resetStick();if(t.identifier===lookId)lookId=null;}});addEventListener('touchcancel',()=>{resetStick();lookId=null;});
function bind(el,fn){el.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();fn();});}bind(ui.use,use);bind(ui.lamp,toggleLamp);addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')use();if(e.code==='KeyF')toggleLamp();});addEventListener('keyup',e=>keys[e.code]=false);ui.startBtn.onclick=()=>{started=true;ui.start.style.display='none';stream();if(ac)ac.resume();};
stream();let last=performance.now(),hudTick=0;function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;if(started){let f=-joyY+(keys.KeyW?1:0)-(keys.KeyS?1:0),s=joyX+(keys.KeyD?1:0)-(keys.KeyA?1:0),n=Math.hypot(f,s);if(n>1){f/=n;s/=n;}const speed=5.8,sn=Math.sin(player.yaw),cs=Math.cos(player.yaw),dx=(s*cs-f*sn)*speed*dt,dz=(-s*sn-f*cs)*speed*dt;const px=player.pos.clone();px.x+=dx;px.y=floorAt(px.x,px.z,player.pos.y-1.67)+1.67;if(!blocked(px))player.pos.copy(px);const pz=player.pos.clone();pz.z+=dz;pz.y=floorAt(pz.x,pz.z,player.pos.y-1.67)+1.67;if(!blocked(pz))player.pos.copy(pz);camera.position.copy(player.pos);camera.rotation.set(player.pitch,player.yaw,0);stream();updateAim();updateEvent(dt);if(now-hudTick>250){hud();hudTick=now;}}renderer.render(scene,camera);}frame(last);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});