import * as THREE from "https://unpkg.com/three@0.160.0/build/three.module.js";
const $=id=>document.getElementById(id),title=$("title"),hint=$("hint"),coords=$("coords"),overlay=$("startOverlay"),startBtn=$("startBtn"),joy=$("joystick"),stick=$("stick"),zap=$("fireBtn");
if(title)title.textContent="STRAWBERRY ROADS";if(hint)hint.textContent="Update 24 loaded: infinite road combat build.";
let started=false,score=0;function start(){started=true;if(overlay)overlay.style.display="none";if(hint)setTimeout(()=>hint.style.opacity=0,3000)}
if(startBtn){startBtn.onclick=start;startBtn.addEventListener("touchstart",e=>{e.preventDefault();e.stopPropagation();start()},{passive:false})}
window.addEventListener("error",e=>{if(hint)hint.textContent="Runtime error: "+e.message});
const scene=new THREE.Scene();scene.background=new THREE.Color(0x88b9dd);scene.fog=new THREE.FogExp2(0x88b9dd,.0038);
const cam=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.08,1600),ren=new THREE.WebGLRenderer({antialias:false,powerPreference:"high-performance"});ren.setPixelRatio(1);ren.setSize(innerWidth,innerHeight);document.body.appendChild(ren.domElement);
scene.add(new THREE.HemisphereLight(0xddf0ff,0x263a27,1.5));const sun=new THREE.DirectionalLight(0xffdfa7,2.2);scene.add(sun);scene.add(sun.target);
const mat={road:new THREE.MeshStandardMaterial({color:0x30343a,roughness:1}),line:new THREE.MeshStandardMaterial({color:0xe0d18a,roughness:.6}),grass:new THREE.MeshStandardMaterial({vertexColors:true,roughness:1}),tree:new THREE.MeshStandardMaterial({color:0x1d4327,flatShading:true}),trunk:new THREE.MeshStandardMaterial({color:0x56351f}),car:new THREE.MeshStandardMaterial({color:0xd33a45}),dark:new THREE.MeshStandardMaterial({color:0x111318}),creature:new THREE.MeshStandardMaterial({color:0x78ff70,emissive:0x153515}),bolt:new THREE.MeshStandardMaterial({color:0x9fe8ff,emissive:0x56ccff})};
const CH=120,LOAD=4,KEEP=7,ROAD=240,RW=18,chunks=new Map(),creatures=[],bolts=[],tmp=new THREE.Object3D();
function hash(x,z){let n=(Math.floor(x)*374761393+Math.floor(z)*668265263)|0;n=(n^(n>>13))*1274126177;return((n^(n>>16))>>>0)/4294967295}function sm(t){return t*t*(3-2*t)}function noise(x,z){const xi=Math.floor(x),zi=Math.floor(z),xf=x-xi,zf=z-zi,u=sm(xf),v=sm(zf),a=hash(xi,zi),b=hash(xi+1,zi),c=hash(xi,zi+1),d=hash(xi+1,zi+1);return THREE.MathUtils.lerp(THREE.MathUtils.lerp(a,b,u),THREE.MathUtils.lerp(c,d,u),v)}
function md(v){let r=((v%ROAD)+ROAD)%ROAD;return Math.min(r,ROAD-r)}function rb(x,z){return Math.max(0,1-Math.min(md(x),md(z))/RW)}function road(x,z,p=7){return md(x)<RW+p||md(z)<RW+p}function h(x,z){return THREE.MathUtils.lerp((noise(x*.012,z*.012)-.5)*7+(noise(x*.04+9,z*.04-7)-.5)*2,.12,rb(x,z))}
function terrain(cx,cz){const g=new THREE.PlaneGeometry(CH,CH,8,8);g.rotateX(-Math.PI/2);const p=g.attributes.position,cols=[];for(let i=0;i<p.count;i++){const x=cx*CH+CH/2+p.getX(i),z=cz*CH+CH/2+p.getZ(i),y=h(x,z),r=rb(x,z);p.setY(i,y);const c=new THREE.Color(r>.02?0x30343a:0x496f34);if(r<.02)c.lerp(new THREE.Color(0x648247),noise(x*.08,z*.08)*.3);cols.push(c.r,c.g,c.b)}g.setAttribute("color",new THREE.Float32BufferAttribute(cols,3));g.computeVertexNormals();const m=new THREE.Mesh(g,mat.grass);m.position.set(cx*CH+CH/2,0,cz*CH+CH/2);return m}
function addRoads(g,cx,cz){const minX=cx*CH,maxX=minX+CH,minZ=cz*CH,maxZ=minZ+CH;for(let x=Math.floor(minX/ROAD)*ROAD;x<=maxX;x+=ROAD){const r=new THREE.Mesh(new THREE.PlaneGeometry(RW*2,CH),mat.road);r.rotation.x=-Math.PI/2;r.position.set(x,.05,cz*CH+CH/2);g.add(r);const l=new THREE.Mesh(new THREE.PlaneGeometry(1,CH),mat.line);l.rotation.x=-Math.PI/2;l.position.set(x,.08,cz*CH+CH/2);g.add(l)}for(let z=Math.floor(minZ/ROAD)*ROAD;z<=maxZ;z+=ROAD){const r=new THREE.Mesh(new THREE.PlaneGeometry(CH,RW*2),mat.road);r.rotation.x=-Math.PI/2;r.position.set(cx*CH+CH/2,.06,z);g.add(r);const l=new THREE.Mesh(new THREE.PlaneGeometry(CH,1),mat.line);l.rotation.x=-Math.PI/2;l.position.set(cx*CH+CH/2,.09,z);g.add(l)}}
const treeGeo=new THREE.ConeGeometry(4,12,8),trunkGeo=new THREE.CylinderGeometry(.45,.7,5,6),creatureGeo=new THREE.SphereGeometry(3.1,10,8);
function makeChunk(cx,cz){const key=cx+","+cz;if(chunks.has(key))return;const g=new THREE.Group();g.add(terrain(cx,cz));addRoads(g,cx,cz);const trees=new THREE.InstancedMesh(treeGeo,mat.tree,16),trunks=new THREE.InstancedMesh(trunkGeo,mat.trunk,16);let ti=0;for(let i=0;i<16;i++){const x=cx*CH+hash(cx*31+i,cz)*CH,z=cz*CH+hash(cx,cz*47+i)*CH,y=h(x,z);if(road(x,z,10))continue;tmp.position.set(x,y+8,z);tmp.scale.set(1,1+hash(i,cz)*.4,1);tmp.rotation.y=hash(i,cx+cz)*6.28;tmp.updateMatrix();trees.setMatrixAt(ti,tmp.matrix);tmp.position.set(x,y+2.5,z);tmp.scale.set(1,1,1);tmp.updateMatrix();trunks.setMatrixAt(ti,tmp.matrix);ti++}trees.count=trunks.count=ti;g.add(trunks,trees);for(let i=0;i<3;i++){const x=cx*CH+hash(cx*91+i,cz*13)*CH,z=cz*CH+hash(cx*17,cz*89+i)*CH;if(road(x,z,22))continue;const c=new THREE.Mesh(creatureGeo,mat.creature);c.position.set(x,h(x,z)+3,z);c.scale.set(1,.9,1.25);g.add(c);creatures.push(c)}scene.add(g);chunks.set(key,g)}
function updateChunks(){const cx=Math.floor(carPos.x/CH),cz=Math.floor(carPos.z/CH);for(let x=cx-LOAD;x<=cx+LOAD;x++)for(let z=cz-LOAD;z<=cz+LOAD;z++)makeChunk(x,z);for(const[key,g]of chunks){const[a,b]=key.split(",").map(Number);if(Math.abs(a-cx)>KEEP||Math.abs(b-cz)>KEEP){scene.remove(g);chunks.delete(key)}}}
const car=new THREE.Group();car.add(new THREE.Mesh(new THREE.BoxGeometry(4.2,1.4,7),mat.car));car.children[0].position.y=1.2;const cab=new THREE.Mesh(new THREE.BoxGeometry(3.2,1.3,2.8),mat.dark);cab.position.set(0,2.25,-.6);car.add(cab);for(const x of[-.75,.75]){const b=new THREE.Mesh(new THREE.CylinderGeometry(.14,.14,2.4,8),mat.bolt);b.rotation.x=Math.PI/2;b.position.set(x,1.55,-4.15);car.add(b)}scene.add(car);const carPos=new THREE.Vector3(8,0,-8);let yaw=0,speed=0,camYaw=0,camPitch=.25;
function blast(){if(!started)return;const dir=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw));for(const side of[-.7,.7]){const m=new THREE.Mesh(new THREE.SphereGeometry(.45,8,6),mat.bolt);m.position.copy(carPos).add(new THREE.Vector3(Math.cos(yaw)*side,2.1,Math.sin(yaw)*-side)).add(dir.clone().multiplyScalar(5));scene.add(m);bolts.push({mesh:m,vel:dir.clone().multiplyScalar(95),life:1.5})}}if(zap){zap.onclick=blast;zap.addEventListener("touchstart",e=>{e.preventDefault();e.stopPropagation();blast()},{passive:false})}
let joyX=0,joyY=0,joyId=null,lookId=null,lx=0,ly=0;function moveStick(t){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=t.clientX-cx,dy=t.clientY-cy,len=Math.hypot(dx,dy),max=r.width*.34,m=Math.min(max,len),nx=len?dx/len:0,ny=len?dy/len:0;joyX=nx*m/max;joyY=ny*m/max;stick.style.transform=`translate(${nx*m}px,${ny*m}px)`}function resetStick(){joyX=joyY=0;joyId=null;stick.style.transform="translate(0,0)"}
addEventListener("touchstart",e=>{if(!started)return;e.preventDefault();for(const t of e.changedTouches){if(t.target===zap)continue;if(t.clientX<innerWidth*.45&&joyId===null){joyId=t.identifier;moveStick(t)}else if(lookId===null){lookId=t.identifier;lx=t.clientX;ly=t.clientY}}},{passive:false});addEventListener("touchmove",e=>{if(!started)return;e.preventDefault();for(const t of e.changedTouches){if(t.identifier===joyId)moveStick(t);if(t.identifier===lookId){camYaw+=(t.clientX-lx)*.003;camPitch=THREE.MathUtils.clamp(camPitch+(t.clientY-ly)*.002,-.25,.75);lx=t.clientX;ly=t.clientY}}},{passive:false});addEventListener("touchend",e=>{for(const t of e.changedTouches){if(t.identifier===joyId)resetStick();if(t.identifier===lookId)lookId=null}});addEventListener("touchcancel",resetStick);
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;if(started){yaw-=joyX*1.9*dt;speed=THREE.MathUtils.lerp(speed,-joyY*34,.08);carPos.x+=Math.sin(yaw)*speed*dt;carPos.z+=Math.cos(yaw)*speed*dt}carPos.y=h(carPos.x,carPos.z);car.position.set(carPos.x,carPos.y,carPos.z);car.rotation.y=yaw;for(let i=bolts.length-1;i>=0;i--){const b=bolts[i];b.life-=dt;b.mesh.position.addScaledVector(b.vel,dt);let remove=b.life<=0;for(const c of creatures){if(c.visible&&b.mesh.position.distanceTo(c.position)<4.2){c.visible=false;remove=true;score++;break}}if(remove){scene.remove(b.mesh);bolts.splice(i,1)}}updateChunks();const look=yaw+Math.PI+camYaw,dist=18;cam.position.set(carPos.x+Math.sin(look)*dist,carPos.y+10+camPitch*10,carPos.z+Math.cos(look)*dist);cam.lookAt(carPos.x,carPos.y+2,carPos.z);sun.position.set(carPos.x-120,carPos.y+160,carPos.z+80);sun.target.position.set(carPos.x,carPos.y,carPos.z);if(coords)coords.innerHTML=`x: ${carPos.x.toFixed(0)}<br>z: ${carPos.z.toFixed(0)}<br>hits: ${score}`;ren.render(scene,cam)}
addEventListener("resize",()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();ren.setSize(innerWidth,innerHeight)});updateChunks();frame(performance.now());
